import type { Scenario } from '../../types';

const h = (hour: number) => hour * 60;

/**
 * Cenário 3 — Agenda da comunidade.
 * Variação A: reservas sem sobreposição (horários colados são permitidos).
 * Variação B: salas e um projetor compartilhado.
 */
export const agenda: Scenario = {
  id: 'agenda',
  number: 3,
  title: 'Agenda da comunidade',
  tag: 'RESERVAS',
  character: {
    name: 'Jurema',
    role: 'Cuida da agenda do Centro Comunitário Morro Azul',
    avatar: { skin: '#C68B59', hair: '#2B1B12', hairStyle: 'longo', shirt: '#B49ADD' },
  },
  place: 'Centro Comunitário Morro Azul',
  problem: 'Grupos chegam no mesmo horário, e o projetor some quando mais precisam.',
  duration: '6 a 8 min',
  toolKind: 'schedule',
  upgrade: 'Quadro de horários iluminado na parede',
  blocks: [
    { id: 'a-obj-reservas', category: 'objetivo', text: 'Quero uma ferramenta para organizar as reservas dos espaços do centro comunitário, sem horários sobrepostos.' },
    { id: 'a-obj-equip', category: 'objetivo', text: 'Quero uma ferramenta para reservar salas e o projetor do centro comunitário, sem que duas atividades contem com o mesmo aparelho ao mesmo tempo.' },
    { id: 'a-obj-vago', category: 'objetivo', text: 'Quero digitalizar o centro comunitário.' },
    { id: 'a-obj-redes', category: 'objetivo', text: 'Quero divulgar os eventos do centro nas redes sociais.' },

    { id: 'a-ctx-centro', category: 'contexto', text: 'O centro comunitário empresta seus espaços para grupos do bairro. As reservas são combinadas por telefone e anotadas em um quadro.' },
    { id: 'a-ctx-choque', category: 'contexto', text: 'Já aconteceu de dois grupos chegarem no mesmo horário para usar o salão.' },
    { id: 'a-ctx-projetor', category: 'contexto', text: 'Temos um único projetor, que circula entre as salas. Já faltou projetor para uma oficina porque ele estava em outra sala.' },
    { id: 'a-ctx-pintura', category: 'contexto', text: 'As paredes do salão foram pintadas de azul no mês passado.' },

    { id: 'a-dad-reserva', category: 'dados', text: 'Para cada reserva, guardar o espaço, o dia, o horário de início, o horário de fim e o grupo responsável.' },
    { id: 'a-dad-equip', category: 'dados', text: 'Em cada reserva, registrar se o projetor vai ser usado.', grants: ['sch.equipment'] },
    { id: 'a-dad-documentos', category: 'dados', text: 'Guardar CPF e telefone pessoal de todos os participantes de cada grupo.' },

    { id: 'a-aco-reservar', category: 'acoes', text: 'Registrar uma nova reserva quando o horário estiver livre.', grants: ['sch.book'] },
    { id: 'a-aco-conflito', category: 'acoes', text: 'Recusar reservas que se sobreponham a outra no mesmo espaço. Uma reserva pode começar exatamente quando outra termina.', grants: ['sch.noOverlap'] },
    { id: 'a-aco-intervalo', category: 'acoes', text: 'Exigir pelo menos 1 hora livre entre duas reservas no mesmo espaço.', grants: ['sch.bufferHour'] },
    { id: 'a-aco-equip', category: 'acoes', text: 'Recusar o projetor quando ele já estiver reservado em outra sala no mesmo horário, e mostrar onde ele está.', grants: ['sch.equipmentConflict'] },
    { id: 'a-aco-cancelar', category: 'acoes', text: 'Permitir cancelar uma reserva, liberando o horário.', grants: ['sch.cancel'] },
    { id: 'a-aco-liberar', category: 'acoes', text: 'Quando uma reserva for cancelada, liberar também o projetor que estava reservado com ela.', grants: ['sch.releaseEquipment'] },

    { id: 'a-res-claro', category: 'restricoes', text: 'Mostrar os horários com início e fim e explicar o motivo quando uma reserva for recusada.' },
    { id: 'a-res-semcancelar', category: 'restricoes', text: 'Não permitir cancelamentos, para evitar confusão na agenda.' },
    { id: 'a-res-celular', category: 'restricoes', text: 'Funcionar bem no celular, porque as reservas são combinadas por telefone.' },
    { id: 'a-res-privacidade', category: 'restricoes', text: 'Não guardar dados pessoais dos participantes. Basta o nome do grupo.' },

    { id: 'a-resu-agenda', category: 'resultado', text: 'Mostrar a agenda do dia de cada espaço, com os horários ocupados e livres.' },
    { id: 'a-resu-equip', category: 'resultado', text: 'Mostrar onde o projetor está em cada horário.' },
    { id: 'a-resu-animacao', category: 'resultado', text: 'Usar muitas animações e efeitos na agenda.' },

    { id: 'a-ver-conflito', category: 'verificacao', text: 'Para conferir: tentar reservar o salão das 15h às 17h, quando ele está ocupado das 14h às 16h. Deve ser recusado.' },
    { id: 'a-ver-colado', category: 'verificacao', text: 'Para conferir: reservar o salão das 16h às 18h, logo depois de uma reserva que termina às 16h. Deve ser aceito.' },
    { id: 'a-ver-projetor', category: 'verificacao', text: 'Para conferir: pedir o projetor para a Sala 2 enquanto ele está na Sala 1 (deve ser recusado) e, depois de cancelar a reserva da Sala 1, ver se ele fica livre.' },
    { id: 'a-ver-vago', category: 'verificacao', text: 'Ver se funciona.' },
  ],
  conflicts: [
    {
      a: 'a-aco-conflito',
      b: 'a-aco-intervalo',
      explanation:
        'Um bloco diz que uma reserva pode começar exatamente quando outra termina; o outro exige 1 hora livre entre reservas. As instruções se contradizem. Lembre o que a responsável disse sobre horários colados.',
    },
    {
      a: 'a-aco-cancelar',
      b: 'a-res-semcancelar',
      explanation: 'Um bloco pede para permitir cancelamentos; o outro proíbe. A IA não consegue seguir os dois.',
    },
    {
      a: 'a-dad-documentos',
      b: 'a-res-privacidade',
      explanation: 'Um bloco pede CPF e telefone dos participantes; o outro pede para não guardar dados pessoais. Escolha um dos dois.',
    },
  ],
  flagTexts: {
    'sch.book': { built: 'Formulário para registrar reservas.', assumption: 'Não incluí o registro de reservas, porque o pedido não falou disso.' },
    'sch.noOverlap': { built: 'Verificação de conflitos de horário no mesmo espaço.', assumption: 'Considerei que cada reserva pedida deve ser registrada.' },
    'sch.bufferHour': { built: 'Intervalo mínimo de 1 hora entre reservas.' },
    'sch.cancel': { built: 'Botão para cancelar reservas.', assumption: 'Não incluí cancelamento, porque o pedido não falou disso.' },
    'sch.equipment': { built: 'Opção de reservar o projetor junto com a sala.', assumption: 'As reservas registram apenas a sala.' },
    'sch.equipmentConflict': { built: 'Verificação de uso do projetor em outra sala no mesmo horário.', assumption: 'Qualquer reserva pode incluir o projetor.' },
    'sch.releaseEquipment': { built: 'Liberação do projetor quando a reserva é cancelada.', assumption: 'Ao cancelar, a sala é liberada.' },
  },
  variations: [
    {
      id: 'agenda-a',
      scenarioId: 'agenda',
      letter: 'A',
      title: 'Horários sem choque',
      situation:
        '“Semana passada, o grupo de capoeira e a feira de trocas chegaram juntos no salão. As reservas estavam no quadro, uma por cima da outra, e ninguém percebeu.”',
      goal: 'Ajudar Jurema a organizar reservas e impedir horários sobrepostos no mesmo espaço — permitindo horários colados.',
      learning: 'Perceber casos-limite (horários que só se encostam) e testar o que deve ser aceito, não só o que deve ser recusado.',
      referenceNote: 'Agenda de sábado, 17/10/2026.',
      questions: [
        {
          id: 'q-quem',
          text: 'Quem vai usar a ferramenta?',
          answer: 'Eu, principalmente, quando os grupos ligam. Às vezes a Dona Neide, que abre o centro de manhã.',
          reveals: ['f-usuarios'],
          why: 'Saber quem usa ajuda a pedir uma tela clara, que funcione no celular durante uma ligação.',
          usefulness: 'util',
        },
        {
          id: 'q-registra',
          text: 'O que você precisa anotar em cada reserva?',
          answer: 'Qual espaço, o dia, a hora de começo, a hora de fim e qual grupo vai usar.',
          reveals: ['f-dados'],
          why: 'Agora você sabe quais informações a ferramenta precisa guardar.',
          usefulness: 'essencial',
        },
        {
          id: 'q-errado',
          text: 'O que costuma dar errado?',
          answer: 'Uma reserva começava antes de a outra terminar, e ninguém viu no quadro. Dois grupos chegaram juntos.',
          reveals: ['f-problema'],
          why: 'O problema real mostra o que a ferramenta não pode deixar acontecer.',
          usefulness: 'essencial',
        },
        {
          id: 'q-conflito',
          text: 'Se alguém pedir um horário que já está ocupado, o que deve acontecer?',
          answer: 'Recusar e mostrar quem está usando, para a pessoa escolher outro horário.',
          reveals: ['f-regra-conflito'],
          why: 'Perguntar “o que deve acontecer quando…” revela a regra principal.',
          usefulness: 'essencial',
        },
        {
          id: 'q-colado',
          text: 'E se uma atividade começa exatamente quando a outra termina?',
          answer: 'Isso pode! Se a associação sai às 16h, o coral pode começar às 16h. Os grupos se ajudam na troca.',
          reveals: ['f-regra-colado'],
          why: 'Situações no limite de uma regra costumam ser esquecidas. Perguntar sobre elas evita que a ferramenta recuse algo permitido.',
          usefulness: 'essencial',
        },
        {
          id: 'q-cancelar',
          text: 'E quando um grupo desiste?',
          answer: 'Preciso conseguir cancelar e deixar o horário livre para outro grupo.',
          reveals: ['f-cancelar'],
          why: 'Você descobriu mais uma ação que a ferramenta precisa ter.',
          usefulness: 'essencial',
        },
        {
          id: 'q-conferir',
          text: 'Como você vai saber que funcionou?',
          answer: 'Reservar das 16h às 18h depois da associação tem que dar certo. Reservar o salão das 15h às 17h tem que ser recusado. E cancelar a capoeira tem que liberar a manhã.',
          reveals: ['f-verificacao'],
          why: 'Esses exemplos viram os testes que você vai fazer depois.',
          usefulness: 'essencial',
        },
        {
          id: 'q-cor',
          text: 'Que cor tem o salão?',
          answer: 'Azul! Pintamos no mês passado. Ficou lindo.',
          reveals: [],
          why: 'Não muda as regras das reservas. Perguntar o que deve acontecer em situações específicas ajuda mais.',
          usefulness: 'pouco-util',
        },
      ],
      facts: [
        { id: 'f-usuarios', kind: 'usuarios', essential: false, text: 'Jurema (por telefone) e Dona Neide, que abre o centro.' },
        {
          id: 'f-dados',
          kind: 'dados',
          essential: true,
          text: 'Espaço, dia, horário de início, horário de fim e grupo responsável.',
          concept: { term: 'Dados', explanation: 'As informações que uma ferramenta guarda são chamadas de dados.' },
        },
        {
          id: 'f-problema',
          kind: 'problema',
          essential: true,
          text: 'Reservas que se sobrepõem passam despercebidas no quadro.',
          concept: { term: 'Sobreposição', explanation: 'Quando dois horários ocupam parte do mesmo tempo, dizemos que eles se sobrepõem.' },
        },
        {
          id: 'f-regra-conflito',
          kind: 'regras',
          essential: true,
          text: 'Pedido em horário ocupado deve ser recusado, mostrando quem está usando.',
          concept: {
            term: 'Regra de negócio',
            explanation: 'Você descobriu uma condição que a solução precisa respeitar: impedir horários sobrepostos no mesmo espaço. Isso é uma regra de negócio.',
          },
        },
        {
          id: 'f-regra-colado',
          kind: 'regras',
          essential: true,
          text: 'Horários colados são permitidos: uma reserva pode começar quando outra termina.',
          concept: {
            term: 'Caso-limite',
            explanation: 'Uma situação bem na fronteira de uma regra — como horários que só se encostam — é chamada de caso-limite. Vale sempre testar.',
          },
        },
        { id: 'f-cancelar', kind: 'regras', essential: true, text: 'Cancelar uma reserva deixa o horário livre para outro grupo.' },
        {
          id: 'f-verificacao',
          kind: 'verificacao',
          essential: true,
          text: '16h–18h depois da associação é aceito; 15h–17h no salão é recusado; cancelar a capoeira libera a manhã.',
          concept: { term: 'Caso de teste', explanation: 'Uma situação concreta usada para conferir se a solução funciona é chamada de caso de teste.' },
        },
      ],
      help: {
        briefing: {
          pista: 'O quadro mostra as reservas, mas não avisa quando duas se cruzam.',
          exemplo: 'Uma reserva das 14h às 16h e outra das 15h às 17h dividem uma hora inteira.',
          direta: 'Clique em “Começar a investigar” para conversar com Jurema.',
        },
        investigate: {
          pista: 'Além do que deve ser recusado, pergunte sobre situações no limite: e se um horário só encosta no outro?',
          exemplo: 'Pergunte: “E se uma atividade começa exatamente quando a outra termina?”',
          direta: 'Faça as perguntas sobre o que anotar, o que dá errado, horário ocupado, horários colados, desistências e como conferir.',
        },
        build: {
          pista: 'Cuidado com regras mais rígidas do que o necessário: elas também são erros.',
          exemplo: 'Exigir 1 hora de intervalo parece prudente, mas recusaria o coral às 16h — e Jurema disse que isso pode.',
          direta: 'Inclua: objetivo sem sobreposição; contexto do centro e do choque; dados da reserva; reservar, recusar sobreposição (permitindo colados) e cancelar; explicar recusas; mostrar a agenda; e os testes de conflito e de horário colado.',
        },
        test: {
          pista: 'Teste o que deve ser aceito e o que deve ser recusado.',
          exemplo: 'Se a reserva das 16h foi recusada, a ferramenta está rígida demais. Se a das 15h foi aceita, está permissiva demais.',
          direta: 'Para reservas por cima de outras, inclua o bloco “Recusar reservas que se sobreponham…”. Se horários colados forem recusados, remova o bloco de intervalo de 1 hora.',
        },
      },
      blockRoles: {
        'a-obj-reservas': { quality: 'essencial', feedback: 'Objetivo claro: reservas sem sobreposição.', missing: 'Falta dizer o objetivo: organizar reservas sem horários sobrepostos.' },
        'a-obj-equip': { quality: 'util', feedback: 'O projetor é o foco da outra variação.' },
        'a-obj-vago': { quality: 'vago', feedback: '“Digitalizar o centro” não diz o que a ferramenta precisa resolver.' },
        'a-obj-redes': { quality: 'irrelevante', feedback: 'Divulgar eventos não resolve o choque de horários.' },
        'a-ctx-centro': { quality: 'essencial', feedback: 'Diz como as reservas acontecem hoje.', missing: 'Conte onde e como as reservas são feitas hoje.' },
        'a-ctx-choque': { quality: 'essencial', feedback: 'Explica o problema real: dois grupos no mesmo horário.', missing: 'Conte o problema de hoje: grupos chegando no mesmo horário.' },
        'a-ctx-projetor': { quality: 'util', feedback: 'Verdade, mas o projetor é o foco da outra variação.' },
        'a-ctx-pintura': { quality: 'irrelevante', feedback: 'A cor das paredes não ajuda a IA a organizar horários.' },
        'a-dad-reserva': { quality: 'essencial', feedback: 'Os dados de cada reserva.', missing: 'Diga quais informações guardar: espaço, dia, início, fim e grupo.' },
        'a-dad-equip': { quality: 'util', feedback: 'Pode ser útil, mas o projetor não é o foco desta variação.' },
        'a-dad-documentos': { quality: 'irrelevante', feedback: 'Dados pessoais de todos os participantes não são necessários para reservar um espaço.' },
        'a-aco-reservar': { quality: 'essencial', feedback: 'Registrar reservas.', missing: 'O pedido precisa dizer que as reservas devem ser registradas.' },
        'a-aco-conflito': { quality: 'essencial', feedback: 'Regra principal, incluindo o caso dos horários colados.', missing: 'Falta dizer o que fazer quando o horário pedido já está ocupado.' },
        'a-aco-intervalo': { quality: 'prejudicial', feedback: 'Exigir 1 hora livre recusa horários colados, que Jurema disse serem permitidos.' },
        'a-aco-equip': { quality: 'irrelevante', feedback: 'Não há projetor para controlar nesta variação.' },
        'a-aco-cancelar': { quality: 'essencial', feedback: 'Permite liberar horários.', missing: 'Falta permitir cancelar reservas.' },
        'a-aco-liberar': { quality: 'irrelevante', feedback: 'Não há projetor para liberar nesta variação.' },
        'a-res-claro': { quality: 'essencial', feedback: 'Explicar recusas ajuda o grupo a escolher outro horário.', missing: 'Peça horários claros e explicação quando algo for recusado.' },
        'a-res-semcancelar': { quality: 'prejudicial', feedback: 'Sem cancelamento, horários de quem desistiu ficam presos.' },
        'a-res-celular': { quality: 'util', feedback: 'Bom cuidado: as reservas são combinadas por telefone.' },
        'a-res-privacidade': { quality: 'util', feedback: 'Bom cuidado: evita guardar dados desnecessários.' },
        'a-resu-agenda': { quality: 'essencial', feedback: 'Mostra horários ocupados e livres.', missing: 'Diga o que mostrar: a agenda de cada espaço.' },
        'a-resu-equip': { quality: 'irrelevante', feedback: 'Não há projetor nesta variação.' },
        'a-resu-animacao': { quality: 'vago', feedback: 'Animações não ajudam a evitar choques de horário.' },
        'a-ver-conflito': { quality: 'essencial', feedback: 'Testa o que deve ser recusado.', missing: 'Inclua um teste de reserva conflitante.' },
        'a-ver-colado': { quality: 'essencial', feedback: 'Testa o caso-limite que deve ser aceito.', missing: 'Inclua um teste com horários colados.' },
        'a-ver-projetor': { quality: 'irrelevante', feedback: 'Não há projetor nesta variação.' },
        'a-ver-vago': { quality: 'vago', feedback: '“Ver se funciona” não diz o que testar.' },
      },
      tool: {
        kind: 'schedule',
        day: 'Sábado, 17/10/2026',
        openHour: 8,
        closeHour: 22,
        spaces: [
          { id: 'salao', name: 'Salão principal' },
          { id: 'reuniao', name: 'Sala de reuniões' },
        ],
        groups: ['Coral do bairro', 'Feira de trocas', 'Aula de dança', 'Grupo de leitura'],
        reservations: [
          { id: 'R1', space: 'salao', start: h(9), end: h(11), group: 'Grupo de capoeira', equipment: false, status: 'ativa', equipmentHeld: false },
          { id: 'R2', space: 'salao', start: h(14), end: h(16), group: 'Associação de moradores', equipment: false, status: 'ativa', equipmentHeld: false },
          { id: 'R3', space: 'reuniao', start: h(10), end: h(12), group: 'Cursinho popular', equipment: false, status: 'ativa', equipmentHeld: false },
        ],
      },
      tests: [
        {
          id: 't-livre',
          title: 'Reservar um horário livre (colado em outro)',
          instruction: 'Reserve o Salão principal das 16:00 às 18:00 para o Coral do bairro. Esse horário começa exatamente quando a reunião da associação termina.',
          expected: 'A reserva é aceita: horários que apenas se encostam não se sobrepõem.',
          check: 'sch.freeAdjacent',
          autoActions: [{ type: 'sch.book', space: 'salao', start: h(16), end: h(18), group: 'Coral do bairro', equipment: false }],
        },
        {
          id: 't-conflito',
          title: 'Tentar uma reserva conflitante',
          instruction: 'Reserve o Salão principal das 15:00 às 17:00 para a Feira de trocas.',
          expected: 'A reserva é recusada e a ferramenta mostra quem já ocupa esse horário.',
          check: 'sch.conflict',
          autoActions: [{ type: 'sch.book', space: 'salao', start: h(15), end: h(17), group: 'Feira de trocas', equipment: false }],
        },
        {
          id: 't-cancelar',
          title: 'Cancelar uma reserva',
          instruction: 'Cancele a reserva do Grupo de capoeira (Salão principal, 09:00 às 11:00).',
          expected: 'A reserva sai da agenda e o horário fica livre.',
          check: 'sch.cancel',
          autoActions: [{ type: 'sch.cancel', reservationId: 'R1' }],
        },
      ],
      impact:
        'Agora cada espaço tem uma agenda sem choques. Grupos podem marcar horários colados, a troca entre atividades é tranquila e um horário cancelado volta a ficar disponível na hora.',
      takeaways: [
        'Casos-limite (horários colados) precisam ser perguntados e testados.',
        'Uma regra rígida demais também é um erro: recusar o que é permitido atrapalha as pessoas.',
        'Bons testes verificam o que deve ser recusado e o que deve ser aceito.',
      ],
    },
    {
      id: 'agenda-b',
      scenarioId: 'agenda',
      letter: 'B',
      title: 'Salas e projetor',
      situation:
        '“Temos um único projetor. Semana passada, a oficina de currículo ficou sem ele porque estava na outra sala. As duas salas estavam livres, mas o aparelho não.”',
      goal: 'Ajudar Jurema a verificar a disponibilidade das salas e do projetor compartilhado.',
      learning: 'Perceber que um recurso compartilhado tem a sua própria agenda, separada da agenda das salas.',
      referenceNote: 'Agenda de sábado, 17/10/2026. O centro tem um único projetor.',
      questions: [
        {
          id: 'q-quem',
          text: 'Quem vai usar a ferramenta?',
          answer: 'Eu, quando os grupos ligam, e quem abre as salas precisa saber onde o projetor deve estar.',
          reveals: ['f-usuarios'],
          why: 'Quem abre as salas precisa ver onde o projetor está em cada horário.',
          usefulness: 'util',
        },
        {
          id: 'q-registra',
          text: 'O que você precisa anotar em cada reserva?',
          answer: 'Sala, dia, começo, fim, grupo — e se vai usar o projetor. Só temos um.',
          reveals: ['f-dados'],
          why: 'Você descobriu um dado a mais: o uso do projetor em cada reserva.',
          usefulness: 'essencial',
        },
        {
          id: 'q-errado',
          text: 'O que costuma dar errado?',
          answer: 'A oficina ficou sem projetor porque ele estava na outra sala. As salas estavam livres, mas o aparelho não.',
          reveals: ['f-problema'],
          why: 'O problema mostra que verificar só a sala não basta.',
          usefulness: 'essencial',
        },
        {
          id: 'q-ocupado',
          text: 'Se pedirem o projetor quando ele já estiver em outra sala, o que deve acontecer?',
          answer: 'Avisar que está ocupado e onde está, e não confirmar a reserva com projetor. A pessoa pode escolher outro horário ou ficar sem.',
          reveals: ['f-regra-equip'],
          why: 'Perguntar “o que deve acontecer quando…” revela a regra principal desta missão.',
          usefulness: 'essencial',
        },
        {
          id: 'q-cancelar',
          text: 'E quando uma reserva é cancelada?',
          answer: 'A sala e o projetor têm que voltar a ficar livres. Hoje o projetor fica “preso” no quadro até alguém lembrar de apagar.',
          reveals: ['f-regra-liberar'],
          why: 'Você descobriu que cancelar precisa liberar duas coisas, não uma.',
          usefulness: 'essencial',
        },
        {
          id: 'q-salas',
          text: 'Quantas salas o centro tem?',
          answer: 'Duas salas pequenas, a Sala 1 e a Sala 2, cada uma com mesas e cadeiras.',
          reveals: ['f-espacos'],
          why: 'Saber quantos espaços existem ajuda a imaginar os testes.',
          usefulness: 'util',
        },
        {
          id: 'q-conferir',
          text: 'Como você vai saber que funcionou?',
          answer: 'Reservar a Sala 2 com projetor das 15h às 17h tem que dar certo. Pedir o projetor para a Sala 2 das 10h às 12h tem que ser recusado, porque ele está na Sala 1. E cancelando a oficina de currículo, o projetor tem que ficar livre.',
          reveals: ['f-verificacao'],
          why: 'Esses exemplos viram os testes que você vai fazer depois.',
          usefulness: 'essencial',
        },
        {
          id: 'q-marca',
          text: 'Qual a marca do projetor?',
          answer: 'Nem sei! É um que ganhamos de doação. Funciona bem.',
          reveals: [],
          why: 'A marca não muda as regras. Perguntar o que acontece quando o projetor já está em uso ajuda mais.',
          usefulness: 'pouco-util',
        },
      ],
      facts: [
        { id: 'f-usuarios', kind: 'usuarios', essential: false, text: 'Jurema e quem abre as salas, que precisa saber onde o projetor estará.' },
        {
          id: 'f-dados',
          kind: 'dados',
          essential: true,
          text: 'Sala, dia, início, fim, grupo e se o projetor será usado.',
          concept: { term: 'Dados', explanation: 'As informações que uma ferramenta guarda são chamadas de dados.' },
        },
        {
          id: 'f-problema',
          kind: 'problema',
          essential: true,
          text: 'As salas estavam livres, mas o único projetor já estava em outra sala.',
          concept: { term: 'Recurso compartilhado', explanation: 'Algo que vários grupos usam, mas só um de cada vez — como o projetor — é um recurso compartilhado.' },
        },
        {
          id: 'f-regra-equip',
          kind: 'regras',
          essential: true,
          text: 'Projetor ocupado em outra sala no mesmo horário: recusar e mostrar onde ele está.',
          concept: {
            term: 'Regra de negócio',
            explanation: 'Você descobriu uma condição que a solução precisa respeitar: o mesmo projetor não pode estar em duas salas ao mesmo tempo. Isso é uma regra de negócio.',
          },
        },
        { id: 'f-regra-liberar', kind: 'regras', essential: true, text: 'Ao cancelar, a sala e o projetor voltam a ficar livres.' },
        { id: 'f-espacos', kind: 'resultado', essential: false, text: 'Duas salas: Sala 1 e Sala 2. Um único projetor.' },
        {
          id: 'f-verificacao',
          kind: 'verificacao',
          essential: true,
          text: 'Sala 2 com projetor às 15h é aceita; projetor na Sala 2 às 10h é recusado; cancelar a oficina libera o projetor.',
          concept: { term: 'Caso de teste', explanation: 'Uma situação concreta usada para conferir se a solução funciona é chamada de caso de teste.' },
        },
      ],
      help: {
        briefing: {
          pista: 'Desta vez o problema não é a sala. O que estava faltando?',
          exemplo: 'Duas salas livres não ajudam se o único projetor está em uma delas.',
          direta: 'Clique em “Começar a investigar” para conversar com Jurema.',
        },
        investigate: {
          pista: 'O projetor tem a sua própria agenda. Pergunte o que acontece quando ele já está em uso e quando uma reserva é cancelada.',
          exemplo: 'Pergunte: “Se pedirem o projetor quando ele já estiver em outra sala, o que deve acontecer?”',
          direta: 'Faça as perguntas sobre o que anotar, o que dá errado, projetor ocupado, cancelamento e como conferir.',
        },
        build: {
          pista: 'Para controlar o projetor, a ferramenta precisa primeiro saber em quais reservas ele está.',
          exemplo: 'Sem “registrar se o projetor vai ser usado”, a regra de não usar o mesmo projetor em duas salas não tem como funcionar.',
          direta: 'Inclua: objetivo com salas e projetor; contexto do centro e do projetor único; dados da reserva e do projetor; reservar, recusar projetor ocupado, cancelar e liberar o projetor; explicar recusas; mostrar onde o projetor está; e o teste do projetor.',
        },
        test: {
          pista: 'Olhe o painel do projetor depois de cada teste. Onde ele está em cada horário?',
          exemplo: 'Se depois de cancelar a oficina o projetor continua ocupado das 9h às 11h, ele não foi liberado.',
          direta: 'Se não há opção de projetor, inclua “registrar se o projetor vai ser usado”. Se ele vai para duas salas, inclua a regra de recusar. Se fica preso após cancelar, inclua “liberar também o projetor”.',
        },
      },
      blockRoles: {
        'a-obj-equip': { quality: 'essencial', feedback: 'Objetivo claro: salas e projetor.', missing: 'Falta dizer o objetivo: reservar salas e o projetor sem uso simultâneo.' },
        'a-obj-reservas': { quality: 'util', feedback: 'Fala de horários, mas não do projetor, que é o problema desta missão.' },
        'a-obj-vago': { quality: 'vago', feedback: '“Digitalizar o centro” não diz o que a ferramenta precisa resolver.' },
        'a-obj-redes': { quality: 'irrelevante', feedback: 'Divulgar eventos não resolve o uso do projetor.' },
        'a-ctx-centro': { quality: 'essencial', feedback: 'Diz como as reservas acontecem hoje.', missing: 'Conte onde e como as reservas são feitas hoje.' },
        'a-ctx-projetor': { quality: 'essencial', feedback: 'Explica o problema real: um único projetor.', missing: 'Conte que há um único projetor e que ele já faltou.' },
        'a-ctx-choque': { quality: 'util', feedback: 'Verdade, mas o foco desta missão é o projetor.' },
        'a-ctx-pintura': { quality: 'irrelevante', feedback: 'A cor das paredes não ajuda a controlar o projetor.' },
        'a-dad-reserva': { quality: 'essencial', feedback: 'Os dados de cada reserva.', missing: 'Diga quais informações guardar: sala, dia, início, fim e grupo.' },
        'a-dad-equip': { quality: 'essencial', feedback: 'Sem esse dado, a ferramenta não sabe onde está o projetor.', missing: 'Falta registrar se o projetor será usado em cada reserva.' },
        'a-dad-documentos': { quality: 'irrelevante', feedback: 'Dados pessoais dos participantes não são necessários para reservar uma sala.' },
        'a-aco-reservar': { quality: 'essencial', feedback: 'Registrar reservas.', missing: 'O pedido precisa dizer que as reservas devem ser registradas.' },
        'a-aco-equip': { quality: 'essencial', feedback: 'Regra principal: o projetor não pode estar em duas salas ao mesmo tempo.', missing: 'Falta dizer o que fazer quando o projetor já está em outra sala.' },
        'a-aco-cancelar': { quality: 'essencial', feedback: 'Permite cancelar reservas.', missing: 'Falta permitir cancelar reservas.' },
        'a-aco-liberar': { quality: 'essencial', feedback: 'Libera o projetor junto com a sala.', missing: 'Falta dizer que o projetor também deve ser liberado no cancelamento.' },
        'a-aco-conflito': { quality: 'util', feedback: 'Boa regra para as salas, mas não controla o projetor.' },
        'a-aco-intervalo': { quality: 'irrelevante', feedback: 'Jurema não pediu intervalo entre reservas; isso só reduziria os horários disponíveis.' },
        'a-res-claro': { quality: 'essencial', feedback: 'Explicar recusas ajuda o grupo a escolher outro horário.', missing: 'Peça horários claros e explicação quando algo for recusado.' },
        'a-res-semcancelar': { quality: 'prejudicial', feedback: 'Sem cancelamento, o projetor nunca é liberado.' },
        'a-res-celular': { quality: 'util', feedback: 'Bom cuidado: as reservas são combinadas por telefone.' },
        'a-res-privacidade': { quality: 'util', feedback: 'Bom cuidado: evita guardar dados desnecessários.' },
        'a-resu-equip': { quality: 'essencial', feedback: 'Mostra onde o projetor está em cada horário.', missing: 'Peça para mostrar onde o projetor está em cada horário.' },
        'a-resu-agenda': { quality: 'essencial', feedback: 'Mostra horários ocupados e livres.', missing: 'Diga o que mostrar: a agenda de cada sala.' },
        'a-resu-animacao': { quality: 'vago', feedback: 'Animações não ajudam a controlar o projetor.' },
        'a-ver-projetor': { quality: 'essencial', feedback: 'Testa a regra principal e a liberação.', missing: 'Inclua um teste com o projetor em duas salas e com o cancelamento.' },
        'a-ver-conflito': { quality: 'util', feedback: 'Bom teste para salas, mas não verifica o projetor.' },
        'a-ver-colado': { quality: 'util', feedback: 'Bom teste para salas, mas não verifica o projetor.' },
        'a-ver-vago': { quality: 'vago', feedback: '“Ver se funciona” não diz o que testar.' },
      },
      tool: {
        kind: 'schedule',
        day: 'Sábado, 17/10/2026',
        openHour: 8,
        closeHour: 22,
        equipmentName: 'Projetor',
        spaces: [
          { id: 'sala1', name: 'Sala 1' },
          { id: 'sala2', name: 'Sala 2' },
        ],
        groups: ['Cineclube', 'Aula de dança', 'Grupo de leitura', 'Reunião de pais'],
        reservations: [
          { id: 'R1', space: 'sala1', start: h(9), end: h(11), group: 'Oficina de currículo', equipment: true, status: 'ativa', equipmentHeld: false },
          { id: 'R2', space: 'sala2', start: h(13), end: h(15), group: 'Roda de conversa', equipment: false, status: 'ativa', equipmentHeld: false },
        ],
      },
      tests: [
        {
          id: 't-sala-equip',
          title: 'Reservar uma sala e o equipamento',
          instruction: 'Reserve a Sala 2 das 15:00 às 17:00, com projetor, para o Cineclube.',
          expected: 'A reserva é aceita com o projetor.',
          check: 'sch.roomWithEquipment',
          autoActions: [{ type: 'sch.book', space: 'sala2', start: h(15), end: h(17), group: 'Cineclube', equipment: true }],
        },
        {
          id: 't-simultaneo',
          title: 'Tentar usar o mesmo equipamento em outra sala',
          instruction: 'Reserve a Sala 2 das 10:00 às 12:00, com projetor, para a Aula de dança. O projetor está na Sala 1 das 09:00 às 11:00.',
          expected: 'A reserva com projetor é recusada e a ferramenta mostra onde ele está.',
          check: 'sch.equipmentClash',
          autoActions: [{ type: 'sch.book', space: 'sala2', start: h(10), end: h(12), group: 'Aula de dança', equipment: true }],
        },
        {
          id: 't-liberar',
          title: 'Liberar a disponibilidade após o cancelamento',
          instruction: 'Cancele a Oficina de currículo (Sala 1, 09:00 às 11:00, com projetor) e veja se o projetor fica livre.',
          expected: 'A Sala 1 e o projetor ficam livres das 09:00 às 11:00.',
          check: 'sch.releaseAfterCancel',
          autoActions: [{ type: 'sch.cancel', reservationId: 'R1' }],
        },
      ],
      impact:
        'Agora cada grupo sabe se terá o projetor antes de chegar. O aparelho não é prometido para duas salas, e um cancelamento libera tudo na hora — sala e projetor.',
      takeaways: [
        'Um recurso compartilhado tem a sua própria agenda, além da agenda das salas.',
        'Uma regra só funciona se o dado existir: sem registrar o projetor, não há como controlá-lo.',
        'Cancelar pode precisar desfazer mais de uma coisa. Teste o que acontece depois do cancelamento.',
      ],
    },
  ],
};
