import type { Scenario } from '../../types';

/**
 * Cenário 1 — Doações em ordem.
 * Variação A: entradas, saídas e limite de estoque.
 * Variação B: lotes com validade, separação de vencidos e bloqueio de entrega.
 */
export const doacoes: Scenario = {
  id: 'doacoes',
  number: 1,
  title: 'Doações em ordem',
  tag: 'ESTOQUE',
  character: {
    name: 'Dona Lúcia',
    role: 'Coordena o ponto de arrecadação da associação de moradores',
    avatar: { skin: '#8D5A3B', hair: '#D9D4CF', hairStyle: 'coque', shirt: '#38BDBB', glasses: true },
  },
  place: 'Ponto de arrecadação da Associação de Moradores do Jardim Esperança',
  problem: 'As anotações do caderno não batem com o que existe na prateleira.',
  duration: '5 a 7 min',
  toolKind: 'inventory',
  upgrade: 'Prateleira de doações organizada, com etiquetas',
  blocks: [
    { id: 'd-obj-estoque', category: 'objetivo', text: 'Quero uma ferramenta simples para controlar as doações que entram e saem do ponto de arrecadação.' },
    { id: 'd-obj-validade', category: 'objetivo', text: 'Quero uma ferramenta para controlar os lotes de alimentos doados e saber o que ainda está dentro da validade.' },
    { id: 'd-obj-vago', category: 'objetivo', text: 'Quero um sistema moderno e completo para a associação.' },
    { id: 'd-obj-site', category: 'objetivo', text: 'Quero um site bonito para divulgar a campanha de arrecadação.' },

    { id: 'd-ctx-ponto', category: 'contexto', text: 'O ponto de arrecadação funciona na associação de moradores. Voluntários registram as doações recebidas e as retiradas feitas pelas famílias.' },
    { id: 'd-ctx-caderno', category: 'contexto', text: 'Hoje tudo é anotado num caderno, e no fim do mês as contas não batem com o que está na prateleira.' },
    { id: 'd-ctx-pereciveis', category: 'contexto', text: 'Recebemos muitos alimentos perecíveis, como leite e iogurte, e às vezes algo vence na prateleira sem ninguém perceber.' },
    { id: 'd-ctx-historia', category: 'contexto', text: 'A associação foi fundada em 1987 por um grupo de vizinhos.' },

    { id: 'd-dad-produto', category: 'dados', text: 'Para cada produto, guardar o nome e a quantidade disponível.' },
    { id: 'd-dad-lote', category: 'dados', text: 'Para cada lote recebido, guardar produto, quantidade e data de validade.', grants: ['inv.expiry'] },
    { id: 'd-dad-familias', category: 'dados', text: 'Guardar CPF, endereço e renda de cada família atendida.' },

    { id: 'd-aco-entrada', category: 'acoes', text: 'Registrar cada doação recebida, somando a quantidade ao estoque do produto.', grants: ['inv.entries'] },
    { id: 'd-aco-saida', category: 'acoes', text: 'Registrar cada retirada ou entrega, descontando a quantidade do estoque.', grants: ['inv.exits'] },
    { id: 'd-aco-limite', category: 'acoes', text: 'Se alguém tentar retirar mais do que existe, recusar a retirada e mostrar quanto há disponível.', grants: ['inv.stockCheck'] },
    { id: 'd-aco-vencido', category: 'acoes', text: 'Impedir a entrega de itens de lotes vencidos e avisar qual lote precisa ser separado.', grants: ['inv.blockExpired'] },

    { id: 'd-res-simples', category: 'restricoes', text: 'Usar palavras simples nas telas, porque voluntários de várias idades vão usar a ferramenta no celular.' },
    { id: 'd-res-negativo', category: 'restricoes', text: 'Nunca bloquear uma retirada, para não atrasar o atendimento. As contas são acertadas depois.', grants: ['inv.allowNegative'] },
    { id: 'd-res-privacidade', category: 'restricoes', text: 'Não pedir dados pessoais das famílias. Basta registrar os produtos.' },
    { id: 'd-res-vencido-ok', category: 'restricoes', text: 'Itens vencidos há poucos dias ainda podem ser entregues normalmente.' },

    { id: 'd-resu-lista', category: 'resultado', text: 'Mostrar uma lista com cada produto e a quantidade atual, atualizada após cada entrada ou saída.' },
    { id: 'd-resu-separado', category: 'resultado', text: 'Na consulta, mostrar separadamente os itens disponíveis e os itens vencidos, usando a data de hoje.', grants: ['inv.separateExpired'] },
    { id: 'd-resu-grafico', category: 'resultado', text: 'Mostrar gráficos coloridos com animações.' },

    { id: 'd-ver-excesso', category: 'verificacao', text: 'Para conferir: tentar retirar 10 garrafas de óleo quando há 6. A retirada deve ser recusada e o estoque deve continuar em 6.' },
    { id: 'd-ver-entrada-saida', category: 'verificacao', text: 'Para conferir: registrar uma doação e uma retirada e ver se o total aumenta e diminui corretamente.' },
    { id: 'd-ver-lotes', category: 'verificacao', text: 'Para conferir: registrar dois lotes do mesmo produto com validades diferentes e ver se aparecem separados.' },
    { id: 'd-ver-vencido', category: 'verificacao', text: 'Para conferir: consultar a disponibilidade e tentar entregar leite do lote que venceu em 10/10/2026. O lote vencido deve aparecer separado e a entrega deve ser recusada.' },
    { id: 'd-ver-vago', category: 'verificacao', text: 'Conferir se está tudo funcionando.' },
  ],
  conflicts: [
    {
      a: 'd-aco-limite',
      b: 'd-res-negativo',
      explanation:
        'Um bloco pede para recusar retiradas maiores que o estoque; o outro pede para nunca bloquear uma retirada. A IA não consegue seguir os dois. Decida qual regra protege melhor o ponto de arrecadação e remova o outro bloco.',
    },
    {
      a: 'd-dad-familias',
      b: 'd-res-privacidade',
      explanation: 'Um bloco pede para guardar CPF, endereço e renda das famílias; o outro pede para não guardar dados pessoais. Escolha um dos dois.',
    },
    {
      a: 'd-aco-vencido',
      b: 'd-res-vencido-ok',
      explanation: 'Um bloco pede para impedir a entrega de itens vencidos; o outro diz que itens vencidos podem ser entregues. As instruções se contradizem.',
    },
  ],
  flagTexts: {
    'inv.entries': { built: 'Formulário para registrar doações recebidas.', assumption: 'Não incluí registro de doações, porque o pedido não falou de entradas.' },
    'inv.exits': { built: 'Formulário para registrar retiradas e entregas.', assumption: 'Não incluí registro de retiradas, porque o pedido não falou de saídas.' },
    'inv.stockCheck': { built: 'Verificação que recusa retiradas maiores que o estoque.', assumption: 'Considerei que toda retirada informada deve ser registrada como foi pedida.' },
    'inv.allowNegative': { built: 'Retiradas nunca são bloqueadas, como foi pedido.' },
    'inv.expiry': { built: 'Registro de lotes com data de validade.', assumption: 'Registrei os produtos apenas por nome e quantidade.' },
    'inv.separateExpired': { built: 'Consulta que separa itens disponíveis e vencidos.', assumption: 'A consulta mostra o total de cada produto.' },
    'inv.blockExpired': { built: 'Bloqueio de entrega para lotes vencidos.', assumption: 'As entregas são feitas a partir dos lotes cadastrados, na ordem em que chegaram.' },
  },
  variations: [
    {
      id: 'doacoes-a',
      scenarioId: 'doacoes',
      letter: 'A',
      title: 'Entradas e saídas',
      situation:
        '“Toda semana chegam doações e saem cestas para as famílias. A gente anota tudo num caderno, mas no fim do mês as contas nunca batem: o caderno diz que tem óleo e a prateleira está vazia.”',
      goal: 'Ajudar Dona Lúcia a controlar entradas e saídas de produtos, impedindo retiradas maiores que o estoque.',
      learning: 'Descobrir uma regra que a solução precisa respeitar e verificar se a ferramenta realmente a cumpre.',
      questions: [
        {
          id: 'q-quem',
          text: 'Quem vai usar a ferramenta?',
          answer: 'Eu e mais quatro voluntários. Cada dia tem uma pessoa diferente no plantão, e quase todo mundo usa o celular.',
          reveals: ['f-usuarios'],
          why: 'Saber quem vai usar ajuda a pedir algo simples, que funcione no celular e que qualquer voluntário entenda.',
          usefulness: 'util',
        },
        {
          id: 'q-registra',
          text: 'O que vocês anotam hoje no caderno?',
          answer: 'Anotamos o que chega — por exemplo, “10 pacotes de feijão” — e o que sai quando uma família retira. Basicamente o nome do produto e a quantidade.',
          reveals: ['f-dados'],
          why: 'Agora você sabe quais informações a ferramenta precisa guardar: produto e quantidade, nas entradas e nas saídas.',
          usefulness: 'essencial',
        },
        {
          id: 'q-errado',
          text: 'O que costuma dar errado?',
          answer: 'No fim do mês o caderno diz que temos 5 garrafas de óleo, mas a prateleira está vazia. Às vezes alguém anota uma retirada maior do que tinha e ninguém percebe na hora.',
          reveals: ['f-problema'],
          why: 'Entender o problema real mostra o que a ferramenta não pode deixar acontecer.',
          usefulness: 'essencial',
        },
        {
          id: 'q-excesso',
          text: 'Se alguém tentar retirar mais produtos do que vocês têm, o que deve acontecer?',
          answer: 'Não pode deixar! Tem que avisar na hora quanto ainda existe, para a gente combinar outra quantidade com a família.',
          reveals: ['f-regra'],
          why: 'Perguntar “o que deve acontecer quando…” revela as condições que a solução precisa respeitar.',
          usefulness: 'essencial',
        },
        {
          id: 'q-familias',
          text: 'Precisa guardar os dados das famílias?',
          answer: 'Prefiro que não. As famílias já passam por muita coisa. A gente só precisa saber quanto saiu de cada produto.',
          reveals: ['f-privacidade'],
          why: 'Saber o que NÃO deve ser feito também orienta a solução — e protege as pessoas atendidas.',
          usefulness: 'util',
        },
        {
          id: 'q-conferir',
          text: 'Como você vai saber que a ferramenta está funcionando?',
          answer: 'Se eu registrar uma doação, o número tem que subir. Se alguém retirar, tem que descer. E se pedirem 10 garrafas de óleo quando só tem 6, a ferramenta tem que recusar.',
          reveals: ['f-verificacao'],
          why: 'Com exemplos concretos, você vai poder testar a solução depois — e pedir para a IA considerar esses casos.',
          usefulness: 'essencial',
        },
        {
          id: 'q-cor',
          text: 'Qual é a cor preferida da associação?',
          answer: 'Verde, como a nossa fachada! Mas acho que isso não muda muito o controle das doações, né?',
          reveals: [],
          why: 'Detalhes visuais podem ser decididos depois. Agora, perguntar como as pessoas trabalham e o que dá errado ajuda mais.',
          usefulness: 'pouco-util',
        },
      ],
      facts: [
        { id: 'f-usuarios', kind: 'usuarios', essential: false, text: 'Voluntários diferentes a cada dia, usando principalmente o celular.' },
        {
          id: 'f-dados',
          kind: 'dados',
          essential: true,
          text: 'Registrar o nome do produto e a quantidade, nas doações que chegam (entradas) e nas retiradas (saídas).',
          concept: { term: 'Dados', explanation: 'As informações que uma ferramenta guarda — como produto e quantidade — são chamadas de dados.' },
        },
        { id: 'f-problema', kind: 'problema', essential: true, text: 'Retiradas maiores que o estoque passam sem ninguém perceber, e o caderno mostra produtos que não existem.' },
        {
          id: 'f-regra',
          kind: 'regras',
          essential: true,
          text: 'Retiradas maiores que o estoque devem ser recusadas, mostrando quanto há disponível.',
          concept: {
            term: 'Regra de negócio',
            explanation:
              'Você descobriu uma condição que a solução precisa respeitar: impedir retiradas maiores que o estoque. Em tecnologia, esse tipo de condição pode ser chamado de regra de negócio.',
          },
        },
        {
          id: 'f-privacidade',
          kind: 'restricoes',
          essential: false,
          text: 'Não guardar dados pessoais das famílias; registrar só os produtos.',
          concept: { term: 'Restrição', explanation: 'Um limite que a solução precisa respeitar — como não guardar dados pessoais — é chamado de restrição.' },
        },
        {
          id: 'f-verificacao',
          kind: 'verificacao',
          essential: true,
          text: 'Doação aumenta o total; retirada diminui; pedir 10 óleos com 6 em estoque deve ser recusado.',
          concept: { term: 'Caso de teste', explanation: 'Uma situação concreta usada para conferir se a solução funciona é chamada de caso de teste.' },
        },
      ],
      help: {
        briefing: {
          pista: 'Leia com calma o que Dona Lúcia contou. Qual é a reclamação principal dela?',
          exemplo: 'Ela diz que “as contas nunca batem”. Isso indica que algo está saindo sem controle.',
          direta: 'Clique em “Começar a investigar” para conversar com Dona Lúcia.',
        },
        investigate: {
          pista: 'Pense no caminho de um produto: ele chega, fica na prateleira e sai. O que pode dar errado em cada parte?',
          exemplo: 'Uma boa pergunta é sobre situações-limite: “Se alguém tentar retirar mais do que existe, o que deve acontecer?”',
          direta: 'Faça as perguntas sobre o que vocês anotam, o que costuma dar errado, o que fazer quando pedirem mais do que existe e como saber se funciona.',
        },
        build: {
          pista: 'Para cada categoria, pergunte-se: a IA sabe isso só com o que eu escrevi? Volte ao painel “O que já descobrimos”.',
          exemplo: 'Se Dona Lúcia disse que retiradas maiores que o estoque não podem acontecer, essa regra precisa estar no pedido em “O que fazer em cada situação”.',
          direta: 'Inclua: o objetivo de controlar entradas e saídas; o contexto do ponto e do caderno; produto e quantidade; registrar doações e retiradas; recusar retiradas maiores que o estoque; palavras simples; a lista de produtos; e os dois testes concretos.',
        },
        test: {
          pista: 'Faça os três testes. Preste atenção especialmente no que acontece quando alguém pede mais do que existe.',
          exemplo: 'No teste de retirada excessiva, confira o número do estoque depois da tentativa. Ele pode ficar negativo?',
          direta: 'Se o estoque ficou negativo, volte ao pedido e inclua o bloco “Se alguém tentar retirar mais do que existe, recusar a retirada…”. Depois, experimente de novo.',
        },
      },
      blockRoles: {
        'd-obj-estoque': { quality: 'essencial', feedback: 'Objetivo claro: controlar o que entra e sai.', missing: 'Falta dizer claramente o objetivo: controlar as doações que entram e saem.' },
        'd-obj-validade': { quality: 'util', feedback: 'Validade é importante, mas o problema de Dona Lúcia nesta missão é a quantidade que sai.' },
        'd-obj-vago': { quality: 'vago', feedback: '“Moderno e completo” não diz o que a ferramenta precisa resolver. A IA vai ter que adivinhar.' },
        'd-obj-site': { quality: 'irrelevante', feedback: 'Um site de divulgação não resolve o controle de estoque que Dona Lúcia pediu.' },
        'd-ctx-ponto': { quality: 'essencial', feedback: 'Bom contexto: diz onde e por quem a ferramenta será usada.', missing: 'Conte onde a ferramenta será usada e quem registra as doações.' },
        'd-ctx-caderno': { quality: 'essencial', feedback: 'Explica o problema atual: as contas não batem.', missing: 'Conte qual é o problema de hoje: as contas do caderno não batem com a prateleira.' },
        'd-ctx-pereciveis': { quality: 'util', feedback: 'Informação verdadeira, mas o foco desta missão é a quantidade, não a validade.' },
        'd-ctx-historia': { quality: 'irrelevante', feedback: 'A história da associação é bonita, mas não ajuda a IA a controlar o estoque.' },
        'd-dad-produto': { quality: 'essencial', feedback: 'A ferramenta precisa saber o produto e a quantidade.', missing: 'Diga quais informações guardar: produto e quantidade.' },
        'd-dad-lote': { quality: 'util', feedback: 'Guardar a validade pode ajudar no futuro, mas não é o que resolve o problema relatado agora.' },
        'd-dad-familias': { quality: 'irrelevante', feedback: 'Dona Lúcia pediu para não guardar dados das famílias. Dados pessoais sem necessidade expõem as pessoas.' },
        'd-aco-entrada': { quality: 'essencial', feedback: 'Registrar as doações que chegam.', missing: 'O pedido precisa dizer que as doações (entradas) devem ser registradas.' },
        'd-aco-saida': { quality: 'essencial', feedback: 'Registrar as retiradas.', missing: 'O pedido precisa dizer que as retiradas (saídas) devem ser registradas.' },
        'd-aco-limite': { quality: 'essencial', feedback: 'Esta é a regra principal da missão.', missing: 'Falta dizer o que fazer quando alguém tenta retirar mais do que existe.' },
        'd-aco-vencido': { quality: 'irrelevante', feedback: 'Nesta variação os produtos não têm validade registrada; essa regra não tem como funcionar sem a data.' },
        'd-res-simples': { quality: 'essencial', feedback: 'Considera quem vai usar: voluntários no celular.', missing: 'Lembre a IA de que voluntários de várias idades vão usar no celular.' },
        'd-res-negativo': { quality: 'prejudicial', feedback: 'Nunca bloquear retiradas é exatamente o que faz as contas não baterem.' },
        'd-res-privacidade': { quality: 'util', feedback: 'Bom cuidado: protege as famílias atendidas.' },
        'd-res-vencido-ok': { quality: 'irrelevante', feedback: 'Validade não é o foco desta variação — e entregar itens vencidos não é seguro.' },
        'd-resu-lista': { quality: 'essencial', feedback: 'Mostra o estoque atualizado depois de cada movimento.', missing: 'Diga o que a ferramenta deve mostrar: a quantidade atual de cada produto.' },
        'd-resu-separado': { quality: 'irrelevante', feedback: 'Sem datas de validade registradas, não há como separar vencidos nesta variação.' },
        'd-resu-grafico': { quality: 'vago', feedback: 'Gráficos animados não ajudam a impedir os erros que Dona Lúcia relatou.' },
        'd-ver-excesso': { quality: 'essencial', feedback: 'Teste concreto da regra principal.', missing: 'Inclua um teste concreto: tentar retirar mais do que existe.' },
        'd-ver-entrada-saida': { quality: 'essencial', feedback: 'Confere se entradas e saídas mudam o total.', missing: 'Inclua um teste de entrada e saída.' },
        'd-ver-lotes': { quality: 'irrelevante', feedback: 'Não há lotes com validade nesta variação.' },
        'd-ver-vencido': { quality: 'irrelevante', feedback: 'Não há validade registrada nesta variação.' },
        'd-ver-vago': { quality: 'vago', feedback: '“Tudo funcionando” não diz o que testar. Situações concretas revelam mais falhas.' },
      },
      tool: {
        kind: 'inventory',
        products: [
          { id: 'arroz', name: 'Arroz 5 kg', unit: 'pacote(s)' },
          { id: 'feijao', name: 'Feijão 1 kg', unit: 'pacote(s)' },
          { id: 'oleo', name: 'Óleo 900 ml', unit: 'garrafa(s)' },
        ],
        lots: [
          { id: 'L1', product: 'arroz', qty: 12 },
          { id: 'L2', product: 'feijao', qty: 8 },
          { id: 'L3', product: 'oleo', qty: 6 },
        ],
      },
      tests: [
        {
          id: 't-doacao',
          title: 'Registrar uma doação',
          instruction: 'Registre a doação de 10 pacotes de Feijão 1 kg.',
          expected: 'A doação é registrada e o feijão passa de 8 para 18 pacotes.',
          check: 'inv.donation',
          autoActions: [{ type: 'inv.donate', product: 'feijao', qty: 10 }],
        },
        {
          id: 't-retirada',
          title: 'Retirar uma quantidade válida',
          instruction: 'Registre a retirada de 4 pacotes de Arroz 5 kg.',
          expected: 'A retirada é registrada e o arroz passa de 12 para 8 pacotes.',
          check: 'inv.withdrawValid',
          autoActions: [{ type: 'inv.withdraw', product: 'arroz', qty: 4 }],
        },
        {
          id: 't-excesso',
          title: 'Tentar retirar mais que o disponível',
          instruction: 'Tente retirar 10 garrafas de Óleo 900 ml (há 6).',
          expected: 'A retirada é recusada, a ferramenta mostra quanto existe e o estoque continua em 6.',
          check: 'inv.withdrawExcess',
          autoActions: [{ type: 'inv.withdraw', product: 'oleo', qty: 10 }],
        },
      ],
      impact:
        'Agora cada retirada é conferida na hora. Os voluntários sabem exatamente quanto existe, as famílias recebem o que foi combinado e o fim do mês deixou de ser um susto.',
      takeaways: [
        'Perguntar “o que deve acontecer quando…” revela regras que ninguém diria espontaneamente.',
        'Uma IA não adivinha regras: se o pedido não fala do limite de estoque, a ferramenta pode aceitar números impossíveis.',
        'Testes com situações concretas (10 óleos quando há 6) mostram falhas que uma resposta confiante esconde.',
      ],
    },
    {
      id: 'doacoes-b',
      scenarioId: 'doacoes',
      letter: 'B',
      title: 'Lotes e validade',
      situation:
        '“Recebemos leite, iogurte e outros alimentos que vencem. Na semana passada, entregamos leite vencido sem perceber. A caixa estava no fundo da prateleira, misturada com as novas.”',
      goal: 'Ajudar Dona Lúcia a controlar lotes com validade, separando o que está disponível do que venceu.',
      learning: 'Perceber que uma regra depende de um dado (a validade) e de uma referência fixa (a data de hoje) para poder ser testada.',
      referenceNote: 'Data de referência da missão: 14/10/2026. Tudo com validade anterior a essa data está vencido.',
      questions: [
        {
          id: 'q-quem',
          text: 'Quem vai usar a ferramenta?',
          answer: 'Os voluntários do plantão. Foi o Seu Ivo quem entregou o leite vencido sem perceber — ele ficou muito chateado, mas não tinha como saber.',
          reveals: ['f-usuarios'],
          why: 'Saber quem usa mostra que a ferramenta precisa avisar sozinha: quem está no plantão não tem tempo de conferir caixa por caixa.',
          usefulness: 'util',
        },
        {
          id: 'q-registra',
          text: 'O que vocês anotam quando chega uma doação?',
          answer: 'Produto e quantidade. A validade a gente não anota — fica só na embalagem. Mas leite e iogurte chegam em levas com datas diferentes.',
          reveals: ['f-dados'],
          why: 'Você descobriu um dado que hoje não é registrado e que é indispensável: a validade de cada leva.',
          usefulness: 'essencial',
        },
        {
          id: 'q-errado',
          text: 'O que costuma dar errado?',
          answer: 'Itens vencem na prateleira sem ninguém perceber. E quando olhamos o total, parece que temos mais do que realmente podemos entregar.',
          reveals: ['f-problema'],
          why: 'O problema tem duas partes: entregar algo vencido e contar vencidos como disponíveis.',
          usefulness: 'essencial',
        },
        {
          id: 'q-hoje',
          text: 'Como saber se um item já venceu?',
          answer: 'Comparando com a data de hoje. Para os testes desta missão, vamos combinar: hoje é 14/10/2026. Tudo com validade antes disso está vencido.',
          reveals: ['f-data'],
          why: 'Uma data de referência fixa permite testar a regra sempre do mesmo jeito.',
          usefulness: 'essencial',
        },
        {
          id: 'q-vencido',
          text: 'Se alguém tentar entregar um item vencido, o que deve acontecer?',
          answer: 'A ferramenta tem que barrar e dizer qual lote está vencido, para a gente separar para descarte.',
          reveals: ['f-regra'],
          why: 'Perguntar “o que deve acontecer quando…” revela a condição que a solução precisa respeitar.',
          usefulness: 'essencial',
        },
        {
          id: 'q-consulta',
          text: 'O que você quer ver quando abrir a ferramenta?',
          answer: 'Quanto tenho para entregar de verdade. Os vencidos têm que aparecer separados; senão, parece que temos mais do que temos.',
          reveals: ['f-resultado'],
          why: 'Você descobriu como a informação precisa aparecer para ser útil no dia a dia.',
          usefulness: 'essencial',
        },
        {
          id: 'q-conferir',
          text: 'Como vamos saber se está funcionando?',
          answer: 'Registrar dois lotes do mesmo produto com datas diferentes e ver se aparecem separados. Consultar e ver o leite vencido fora da conta. E tentar entregar o leite vencido — tem que ser recusado.',
          reveals: ['f-verificacao'],
          why: 'Esses exemplos viram os testes que você vai fazer depois.',
          usefulness: 'essencial',
        },
        {
          id: 'q-marca',
          text: 'Que marcas de leite vocês recebem mais?',
          answer: 'Ah, varia muito, depende de quem doa. Por quê?',
          reveals: [],
          why: 'A marca não muda o que a ferramenta precisa fazer. Perguntar sobre datas e sobre o que deve acontecer em cada situação ajuda mais.',
          usefulness: 'pouco-util',
        },
      ],
      facts: [
        { id: 'f-usuarios', kind: 'usuarios', essential: false, text: 'Voluntários do plantão, sem tempo para conferir cada embalagem.' },
        {
          id: 'f-dados',
          kind: 'dados',
          essential: true,
          text: 'Cada leva (lote) precisa de produto, quantidade e data de validade.',
          concept: { term: 'Lote', explanation: 'Um conjunto de itens que chegou junto e tem a mesma validade é chamado de lote.' },
        },
        { id: 'f-problema', kind: 'problema', essential: true, text: 'Itens vencem sem ninguém perceber, e o total inclui produtos que não podem ser entregues.' },
        {
          id: 'f-data',
          kind: 'regras',
          essential: true,
          text: 'Hoje, na missão, é 14/10/2026. Validade anterior a essa data significa item vencido.',
          concept: {
            term: 'Data de referência',
            explanation: 'Uma data fixa usada para comparar e testar regras de tempo, sempre com o mesmo resultado, é uma data de referência.',
          },
        },
        {
          id: 'f-regra',
          kind: 'regras',
          essential: true,
          text: 'Entregas de lotes vencidos devem ser bloqueadas, com aviso de qual lote separar.',
          concept: {
            term: 'Regra de negócio',
            explanation: 'Você descobriu uma condição que a solução precisa respeitar: não entregar itens vencidos. Em tecnologia, isso pode ser chamado de regra de negócio.',
          },
        },
        {
          id: 'f-resultado',
          kind: 'resultado',
          essential: true,
          text: 'Mostrar separados os itens disponíveis e os vencidos.',
          concept: { term: 'Resultado esperado', explanation: 'O que a pessoa precisa ver ou receber da ferramenta é o resultado esperado.' },
        },
        {
          id: 'f-verificacao',
          kind: 'verificacao',
          essential: true,
          text: 'Dois lotes com datas diferentes aparecem separados; a consulta separa vencidos; entregar leite vencido é recusado.',
          concept: { term: 'Caso de teste', explanation: 'Uma situação concreta usada para conferir se a solução funciona é chamada de caso de teste.' },
        },
      ],
      help: {
        briefing: {
          pista: 'O problema desta vez não é a quantidade, e sim o tempo. O que muda de um dia para o outro em um alimento?',
          exemplo: 'Um leite que estava bom ontem pode estar vencido hoje. A ferramenta precisa saber disso.',
          direta: 'Clique em “Começar a investigar” para conversar com Dona Lúcia.',
        },
        investigate: {
          pista: 'Para saber se algo venceu, que informação a ferramenta precisa ter? E com qual data ela compara?',
          exemplo: 'Pergunte como saber se um item venceu e o que deve acontecer se alguém tentar entregar algo vencido.',
          direta: 'Faça as perguntas sobre o que é anotado, o que dá errado, como saber se venceu, o que fazer com vencidos, o que ela quer ver e como conferir.',
        },
        build: {
          pista: 'Uma regra sobre validade só funciona se a validade for registrada. Confira se o pedido tem as duas coisas.',
          exemplo: 'Pedir para “bloquear vencidos” sem pedir para “guardar a data de validade de cada lote” deixa a IA sem como saber o que venceu.',
          direta: 'Inclua: o objetivo sobre lotes e validade; o contexto do ponto e dos perecíveis; guardar lote com validade; registrar doações e entregas; bloquear vencidos; palavras simples; consulta separando vencidos; e os testes de lotes e de leite vencido.',
        },
        test: {
          pista: 'Use a data de referência (14/10/2026). O lote de leite que venceu em 10/10/2026 é o mais importante para testar.',
          exemplo: 'Na consulta, compare a quantidade de leite disponível com a soma dos lotes. Os vencidos estão sendo contados?',
          direta: 'Se a ferramenta não tem campo de validade, falta o bloco de lotes com validade. Se vencidos aparecem como disponíveis ou são entregues, faltam os blocos de consulta separada e de bloqueio de vencidos.',
        },
      },
      blockRoles: {
        'd-obj-validade': { quality: 'essencial', feedback: 'Objetivo claro: lotes e validade.', missing: 'Falta dizer o objetivo: controlar lotes e saber o que está dentro da validade.' },
        'd-obj-estoque': { quality: 'util', feedback: 'Controlar entradas e saídas ajuda, mas não menciona a validade, que é o problema desta missão.' },
        'd-obj-vago': { quality: 'vago', feedback: '“Moderno e completo” não diz o que a ferramenta precisa resolver.' },
        'd-obj-site': { quality: 'irrelevante', feedback: 'Um site de divulgação não ajuda a evitar a entrega de itens vencidos.' },
        'd-ctx-ponto': { quality: 'essencial', feedback: 'Diz onde e por quem a ferramenta será usada.', missing: 'Conte onde a ferramenta será usada e quem registra as doações.' },
        'd-ctx-pereciveis': { quality: 'essencial', feedback: 'Explica o problema real: itens vencem sem ninguém perceber.', missing: 'Conte que chegam alimentos perecíveis e que itens vencem sem ninguém perceber.' },
        'd-ctx-caderno': { quality: 'util', feedback: 'Ajuda a entender a rotina, mas o problema principal agora é a validade.' },
        'd-ctx-historia': { quality: 'irrelevante', feedback: 'A história da associação não ajuda a IA a controlar validades.' },
        'd-dad-lote': { quality: 'essencial', feedback: 'Sem a data de validade de cada lote, nenhuma regra sobre vencidos funciona.', missing: 'Falta pedir para guardar a data de validade de cada lote.' },
        'd-dad-produto': { quality: 'util', feedback: 'Produto e quantidade ajudam, mas sozinhos não dizem o que venceu.' },
        'd-dad-familias': { quality: 'irrelevante', feedback: 'Dados pessoais das famílias não são necessários e expõem as pessoas.' },
        'd-aco-entrada': { quality: 'essencial', feedback: 'Registrar as doações (lotes) que chegam.', missing: 'O pedido precisa dizer que as doações devem ser registradas.' },
        'd-aco-saida': { quality: 'essencial', feedback: 'Registrar as entregas.', missing: 'O pedido precisa dizer que as entregas (saídas) devem ser registradas.' },
        'd-aco-vencido': { quality: 'essencial', feedback: 'Esta é a regra principal da missão.', missing: 'Falta dizer o que fazer quando alguém tenta entregar um item vencido.' },
        'd-aco-limite': { quality: 'util', feedback: 'Boa regra para qualquer estoque, mas não resolve o problema da validade.' },
        'd-res-simples': { quality: 'essencial', feedback: 'Considera quem vai usar: voluntários no celular.', missing: 'Lembre a IA de que voluntários de várias idades vão usar no celular.' },
        'd-res-negativo': { quality: 'prejudicial', feedback: 'Nunca bloquear retiradas impede justamente que a ferramenta barre itens vencidos ou em falta.' },
        'd-res-privacidade': { quality: 'util', feedback: 'Bom cuidado: protege as famílias atendidas.' },
        'd-res-vencido-ok': { quality: 'prejudicial', feedback: 'Entregar itens vencidos é o problema que Dona Lúcia quer evitar.' },
        'd-resu-separado': { quality: 'essencial', feedback: 'Mostra o que realmente pode ser entregue.', missing: 'Diga o que mostrar: disponíveis e vencidos separados, usando a data de hoje.' },
        'd-resu-lista': { quality: 'util', feedback: 'Uma lista ajuda, mas sem separar vencidos o total engana.' },
        'd-resu-grafico': { quality: 'vago', feedback: 'Gráficos animados não ajudam a evitar a entrega de itens vencidos.' },
        'd-ver-lotes': { quality: 'essencial', feedback: 'Testa se a validade de cada lote é guardada.', missing: 'Inclua um teste com dois lotes de datas diferentes.' },
        'd-ver-vencido': { quality: 'essencial', feedback: 'Testa a consulta e a regra principal com um caso real.', missing: 'Inclua um teste com o leite que venceu em 10/10/2026.' },
        'd-ver-excesso': { quality: 'util', feedback: 'Teste útil para estoque, mas não verifica a validade.' },
        'd-ver-entrada-saida': { quality: 'util', feedback: 'Confere o total, mas não a validade.' },
        'd-ver-vago': { quality: 'vago', feedback: '“Tudo funcionando” não diz o que testar.' },
      },
      tool: {
        kind: 'inventory',
        referenceDate: '2026-10-14',
        products: [
          { id: 'leite', name: 'Leite 1 L', unit: 'caixa(s)' },
          { id: 'iogurte', name: 'Iogurte', unit: 'unidade(s)' },
          { id: 'macarrao', name: 'Macarrão 500 g', unit: 'pacote(s)' },
        ],
        lots: [
          { id: 'L1', product: 'leite', qty: 6, expiry: '2026-10-10' },
          { id: 'L2', product: 'leite', qty: 10, expiry: '2026-10-20' },
          { id: 'L3', product: 'macarrao', qty: 15, expiry: '2027-01-30' },
        ],
      },
      tests: [
        {
          id: 't-lotes',
          title: 'Registrar lotes com datas diferentes',
          instruction: 'Registre 8 unidades de Iogurte com validade 16/10/2026 e outras 8 com validade 25/10/2026.',
          expected: 'Os dois lotes aparecem separados, cada um com sua validade.',
          check: 'inv.lotsDifferentDates',
          autoActions: [
            { type: 'inv.donate', product: 'iogurte', qty: 8, expiry: '2026-10-16' },
            { type: 'inv.donate', product: 'iogurte', qty: 8, expiry: '2026-10-25' },
          ],
        },
        {
          id: 't-consulta',
          title: 'Consultar a disponibilidade',
          instruction: 'Use o botão de consulta de disponibilidade.',
          expected: 'O leite aparece com 10 caixas disponíveis e 6 vencidas, separadas.',
          check: 'inv.queryAvailability',
          autoActions: [{ type: 'inv.query' }],
        },
        {
          id: 't-vencido',
          title: 'Tentar distribuir um item vencido',
          instruction: 'Tente entregar 2 caixas de Leite 1 L do lote L1 (validade 10/10/2026).',
          expected: 'A entrega é recusada e a ferramenta avisa que o lote L1 está vencido.',
          check: 'inv.distributeExpired',
          autoActions: [{ type: 'inv.withdraw', product: 'leite', qty: 2, lotId: 'L1' }],
        },
      ],
      impact:
        'Os lotes vencidos agora aparecem separados e não podem ser entregues por engano. Os voluntários do plantão confiam no que a tela mostra, e as famílias recebem alimentos dentro da validade.',
      takeaways: [
        'Uma regra (bloquear vencidos) depende de um dado (a validade). Sem pedir os dois, a regra não funciona.',
        'Uma data de referência fixa torna os testes de tempo repetíveis.',
        'Copiar o pedido de outra situação não basta: cada problema tem suas próprias necessidades.',
      ],
    },
  ],
};
