import type { Scenario } from '../../types';

/**
 * Cenário 2 — Vagas para aprender.
 * Variação A: limite de vagas e inscrições repetidas.
 * Variação B: lista de espera e promoção na ordem de chegada.
 */
export const vagas: Scenario = {
  id: 'vagas',
  number: 2,
  title: 'Vagas para aprender',
  tag: 'INSCRIÇÕES',
  character: {
    name: 'Rafael',
    role: 'Coordena os cursos gratuitos da Biblioteca Comunitária Vila Aurora',
    avatar: { skin: '#5A3825', hair: '#1E1414', hairStyle: 'cacheado', shirt: '#EFBA3D' },
  },
  place: 'Biblioteca Comunitária Vila Aurora',
  problem: 'Vagas somem na planilha, e quem espera nem sempre é chamado.',
  duration: '5 a 8 min',
  toolKind: 'enrollment',
  upgrade: 'Mural de turmas com vagas atualizadas',
  blocks: [
    { id: 'v-obj-inscricoes', category: 'objetivo', text: 'Quero uma ferramenta para organizar as inscrições nos cursos gratuitos da biblioteca, respeitando as vagas de cada turma.' },
    { id: 'v-obj-fila', category: 'objetivo', text: 'Quero uma ferramenta para organizar as inscrições e a lista de espera dos cursos, para que nenhuma vaga fique parada.' },
    { id: 'v-obj-vago', category: 'objetivo', text: 'Quero um aplicativo inovador para a educação.' },
    { id: 'v-obj-certificado', category: 'objetivo', text: 'Quero gerar certificados bonitos no fim dos cursos.' },

    { id: 'v-ctx-biblioteca', category: 'contexto', text: 'A biblioteca oferece cursos gratuitos com poucas vagas por turma. As inscrições são feitas no balcão e por mensagem.' },
    { id: 'v-ctx-repetida', category: 'contexto', text: 'Hoje usamos uma planilha compartilhada, e a mesma pessoa às vezes aparece duas vezes na mesma turma, ocupando duas vagas.' },
    { id: 'v-ctx-desistencia', category: 'contexto', text: 'Muita gente desiste na primeira semana, e as vagas ficam vazias enquanto há pessoas esperando.' },
    { id: 'v-ctx-predio', category: 'contexto', text: 'O prédio da biblioteca foi reformado no ano passado.' },

    { id: 'v-dad-inscricao', category: 'dados', text: 'Para cada inscrição, guardar o nome da pessoa e a turma escolhida.' },
    { id: 'v-dad-vagas', category: 'dados', text: 'Para cada turma, guardar o número máximo de vagas.' },
    { id: 'v-dad-ordem', category: 'dados', text: 'Na lista de espera, guardar a ordem de chegada de cada pessoa.' },
    { id: 'v-dad-documentos', category: 'dados', text: 'Guardar RG, CPF e comprovante de residência de cada pessoa.' },

    { id: 'v-aco-inscrever', category: 'acoes', text: 'Registrar inscrições confirmadas enquanto houver vaga na turma.', grants: ['enr.enroll'] },
    { id: 'v-aco-limite', category: 'acoes', text: 'Quando a turma estiver cheia, não confirmar novas inscrições.', grants: ['enr.capacity'] },
    { id: 'v-aco-duplicada', category: 'acoes', text: 'Se a pessoa já estiver inscrita na mesma turma, avisar e não criar outra inscrição.', grants: ['enr.noDuplicate'] },
    { id: 'v-aco-cancelar', category: 'acoes', text: 'Permitir cancelar uma inscrição confirmada, liberando a vaga.', grants: ['enr.cancel'] },
    { id: 'v-aco-espera', category: 'acoes', text: 'Quando a turma estiver cheia, colocar a pessoa na lista de espera e informar sua posição.', grants: ['enr.waitlist'] },
    { id: 'v-aco-promover', category: 'acoes', text: 'Quando uma vaga abrir, confirmar automaticamente a primeira pessoa da lista de espera e avisar quem foi chamado.', grants: ['enr.promoteFirst'] },
    { id: 'v-aco-ultimo', category: 'acoes', text: 'Quando uma vaga abrir, chamar a pessoa que entrou por último na lista, porque o interesse dela é mais recente.', grants: ['enr.promoteLast'] },

    { id: 'v-res-claras', category: 'restricoes', text: 'Explicar o motivo de cada recusa em linguagem simples, como “turma cheia” ou “inscrição já existe”.' },
    { id: 'v-res-justica', category: 'restricoes', text: 'Ninguém pode passar na frente de quem chegou antes: a ordem de chegada deve ser respeitada.' },
    { id: 'v-res-lotar', category: 'restricoes', text: 'Nunca recusar ninguém. É melhor a turma lotar demais do que deixar alguém de fora.', grants: ['enr.overbook'] },
    { id: 'v-res-dados', category: 'restricoes', text: 'Não pedir documentos. Nome e turma bastam.' },

    { id: 'v-resu-turmas', category: 'resultado', text: 'Mostrar, para cada turma, quantas vagas estão ocupadas e quem está inscrito.' },
    { id: 'v-resu-fila', category: 'resultado', text: 'Mostrar a lista de espera de cada turma, em ordem, com a posição de cada pessoa.' },
    { id: 'v-resu-ranking', category: 'resultado', text: 'Mostrar um ranking das pessoas que mais fizeram cursos.' },

    { id: 'v-ver-repetida', category: 'verificacao', text: 'Para conferir: inscrever a mesma pessoa duas vezes na mesma turma. A segunda tentativa deve ser recusada.' },
    { id: 'v-ver-cheia', category: 'verificacao', text: 'Para conferir: tentar inscrever alguém em uma turma cheia. A inscrição não pode ser confirmada.' },
    { id: 'v-ver-fila', category: 'verificacao', text: 'Para conferir: com duas pessoas na lista de espera, cancelar uma inscrição e ver se a primeira da fila foi chamada.' },
    { id: 'v-ver-vago', category: 'verificacao', text: 'Testar tudo direitinho.' },
  ],
  conflicts: [
    {
      a: 'v-aco-limite',
      b: 'v-res-lotar',
      explanation: 'Um bloco pede para não confirmar inscrições em turma cheia; o outro pede para nunca recusar ninguém. A IA não consegue seguir os dois.',
    },
    {
      a: 'v-aco-promover',
      b: 'v-aco-ultimo',
      explanation: 'Um bloco pede para chamar a primeira pessoa da fila; o outro, a última. Quando uma vaga abrir, a IA não saberia quem chamar.',
    },
    {
      a: 'v-res-justica',
      b: 'v-aco-ultimo',
      explanation: 'Chamar quem entrou por último faz essa pessoa passar na frente de quem chegou antes — o contrário do que o outro bloco pede.',
    },
    {
      a: 'v-dad-documentos',
      b: 'v-res-dados',
      explanation: 'Um bloco pede para guardar documentos; o outro pede para não pedir documentos. Escolha um dos dois.',
    },
  ],
  flagTexts: {
    'enr.enroll': { built: 'Formulário de inscrição por turma.', assumption: 'Não incluí inscrições, porque o pedido não falou disso.' },
    'enr.capacity': { built: 'Controle do número máximo de vagas.', assumption: 'Considerei que todas as inscrições pedidas devem ser aceitas.' },
    'enr.overbook': { built: 'Inscrições nunca são recusadas, como foi pedido.' },
    'enr.noDuplicate': { built: 'Aviso de inscrição repetida na mesma turma.', assumption: 'Cada pedido de inscrição gera uma nova linha na turma.' },
    'enr.cancel': { built: 'Botão para cancelar inscrições.', assumption: 'Não incluí cancelamento, porque o pedido não falou disso.' },
    'enr.waitlist': { built: 'Lista de espera para turmas cheias.', assumption: 'Quando a turma enche, a inscrição simplesmente não é feita.' },
    'enr.promoteFirst': { built: 'Chamada automática da primeira pessoa da fila quando uma vaga abre.', assumption: 'Quando uma vaga abre, ela fica disponível para a próxima inscrição.' },
    'enr.promoteLast': { built: 'Chamada automática da pessoa mais recente da fila quando uma vaga abre.' },
  },
  variations: [
    {
      id: 'vagas-a',
      scenarioId: 'vagas',
      letter: 'A',
      title: 'Vagas e inscrições repetidas',
      situation:
        '“Nossos cursos lotam em poucas horas. Mas, quando a turma começa, sempre tem computador sobrando. Descobrimos que algumas pessoas estavam inscritas duas vezes na planilha.”',
      goal: 'Ajudar Rafael a controlar as vagas de cada turma e impedir inscrições repetidas.',
      learning: 'Identificar duas regras diferentes (limite de vagas e duplicidade) e testar cada uma separadamente.',
      questions: [
        {
          id: 'q-quem',
          text: 'Quem vai usar a ferramenta?',
          answer: 'Eu e a Cris, que fica no balcão. As pessoas se inscrevem com a gente, pessoalmente ou por mensagem.',
          reveals: ['f-usuarios'],
          why: 'Duas pessoas registrando por canais diferentes: isso explica por que a mesma inscrição aparece duas vezes.',
          usefulness: 'util',
        },
        {
          id: 'q-registra',
          text: 'O que você precisa registrar em cada inscrição?',
          answer: 'O nome da pessoa e a turma. E cada turma tem um número de vagas, porque o laboratório só tem alguns computadores.',
          reveals: ['f-dados'],
          why: 'Agora você sabe quais informações a ferramenta precisa guardar: nome, turma e limite de vagas.',
          usefulness: 'essencial',
        },
        {
          id: 'q-errado',
          text: 'O que costuma dar errado?',
          answer: 'A mesma pessoa se inscreve no balcão e depois por mensagem. Aparece duas vezes na planilha e ocupa duas vagas. A turma parece cheia, mas não está.',
          reveals: ['f-problema'],
          why: 'O problema real mostra uma regra escondida: a mesma pessoa não pode ocupar duas vagas.',
          usefulness: 'essencial',
        },
        {
          id: 'q-repetida',
          text: 'Se alguém tentar se inscrever de novo na mesma turma, o que deve acontecer?',
          answer: 'Avisar que a pessoa já está inscrita e não criar outra inscrição.',
          reveals: ['f-regra-duplicada'],
          why: 'Perguntar “o que deve acontecer quando…” revela as condições que a solução precisa respeitar.',
          usefulness: 'essencial',
        },
        {
          id: 'q-sem-vagas',
          text: 'O que deve acontecer quando não houver vagas?',
          answer: 'Não pode confirmar. A turma de planilhas tem 2 computadores para 2 pessoas. Se confirmar mais gente, alguém fica sem máquina.',
          reveals: ['f-regra-capacidade'],
          why: 'Você descobriu um limite que a ferramenta precisa respeitar.',
          usefulness: 'essencial',
        },
        {
          id: 'q-conferir',
          text: 'Como você vai saber que funcionou?',
          answer: 'Inscrever alguém em uma turma com vaga tem que dar certo. Repetir a inscrição do Joaquim tem que ser recusado. E ninguém novo entra na turma de planilhas, que já está cheia.',
          reveals: ['f-verificacao'],
          why: 'Esses exemplos viram os testes que você vai fazer depois.',
          usefulness: 'essencial',
        },
        {
          id: 'q-procurado',
          text: 'Qual curso é o mais procurado?',
          answer: 'Informática básica, de longe! Mas todos lotam rápido.',
          reveals: [],
          why: 'É bom saber, mas não muda as regras da ferramenta. Perguntar o que deve acontecer em situações específicas ajuda mais.',
          usefulness: 'pouco-util',
        },
      ],
      facts: [
        { id: 'f-usuarios', kind: 'usuarios', essential: false, text: 'Rafael e Cris registram inscrições no balcão e por mensagem.' },
        {
          id: 'f-dados',
          kind: 'dados',
          essential: true,
          text: 'Nome da pessoa, turma escolhida e número máximo de vagas de cada turma.',
          concept: { term: 'Dados', explanation: 'As informações que uma ferramenta guarda — como nome, turma e número de vagas — são chamadas de dados.' },
        },
        { id: 'f-problema', kind: 'problema', essential: true, text: 'A mesma pessoa aparece duas vezes e ocupa duas vagas; a turma parece cheia sem estar.' },
        {
          id: 'f-regra-duplicada',
          kind: 'regras',
          essential: true,
          text: 'Uma pessoa já inscrita na turma não pode ser inscrita de novo nela.',
          concept: { term: 'Duplicidade', explanation: 'Quando o mesmo registro aparece duas vezes, dizemos que há duplicidade. Impedir isso é uma regra de negócio.' },
        },
        {
          id: 'f-regra-capacidade',
          kind: 'regras',
          essential: true,
          text: 'Turma cheia não aceita novas inscrições confirmadas.',
          concept: { term: 'Capacidade', explanation: 'O número máximo de vagas de uma turma é a sua capacidade.' },
        },
        {
          id: 'f-verificacao',
          kind: 'verificacao',
          essential: true,
          text: 'Inscrição com vaga é aceita; repetir o Joaquim é recusado; turma de planilhas cheia não aceita mais ninguém.',
          concept: { term: 'Caso de teste', explanation: 'Uma situação concreta usada para conferir se a solução funciona é chamada de caso de teste.' },
        },
      ],
      help: {
        briefing: {
          pista: 'Rafael diz que a turma lota, mas sobra computador. Como isso é possível?',
          exemplo: 'Se a mesma pessoa ocupa duas vagas, a turma parece cheia com gente faltando.',
          direta: 'Clique em “Começar a investigar” para conversar com Rafael.',
        },
        investigate: {
          pista: 'Há duas situações em que uma inscrição não deveria ser confirmada. Quais são?',
          exemplo: 'Pergunte: “O que deve acontecer quando não houver vagas?”',
          direta: 'Faça as perguntas sobre o que registrar, o que dá errado, inscrição repetida, turma sem vagas e como saber se funcionou.',
        },
        build: {
          pista: 'Saber o número de vagas não é o mesmo que respeitá-lo. Confira se o pedido diz o que FAZER quando a turma enche.',
          exemplo: 'O bloco “Para cada turma, guardar o número máximo de vagas” guarda o dado; o bloco “Quando a turma estiver cheia, não confirmar…” cria a regra.',
          direta: 'Inclua: objetivo de respeitar vagas; contexto da biblioteca e da planilha; nome, turma e vagas; inscrever, limitar e barrar repetidas; mensagens claras; mostrar turmas; e os testes de repetição e turma cheia.',
        },
        test: {
          pista: 'Faça cada teste e olhe a contagem de vagas da turma depois.',
          exemplo: 'Se o Joaquim aparece duas vezes em Informática básica, a regra de duplicidade não está no pedido.',
          direta: 'Para turma cheia aceitando gente, inclua “Quando a turma estiver cheia, não confirmar novas inscrições”. Para repetição aceita, inclua “Se a pessoa já estiver inscrita…”.',
        },
      },
      blockRoles: {
        'v-obj-inscricoes': { quality: 'essencial', feedback: 'Objetivo claro: inscrições respeitando as vagas.', missing: 'Falta dizer o objetivo: organizar inscrições respeitando as vagas.' },
        'v-obj-fila': { quality: 'util', feedback: 'Lista de espera pode ser útil, mas o problema relatado agora é de vagas e repetições.' },
        'v-obj-vago': { quality: 'vago', feedback: '“Inovador” não diz o que a ferramenta precisa resolver.' },
        'v-obj-certificado': { quality: 'irrelevante', feedback: 'Certificados não resolvem o problema das vagas.' },
        'v-ctx-biblioteca': { quality: 'essencial', feedback: 'Diz onde e como as inscrições acontecem.', missing: 'Conte onde os cursos acontecem e como as inscrições são feitas.' },
        'v-ctx-repetida': { quality: 'essencial', feedback: 'Explica o problema de hoje: inscrições duplicadas.', missing: 'Conte o problema de hoje: a mesma pessoa aparece duas vezes.' },
        'v-ctx-desistencia': { quality: 'util', feedback: 'Verdade, mas desistências são o foco da outra variação.' },
        'v-ctx-predio': { quality: 'irrelevante', feedback: 'A reforma do prédio não ajuda a IA a controlar vagas.' },
        'v-dad-inscricao': { quality: 'essencial', feedback: 'Nome e turma de cada inscrição.', missing: 'Diga quais informações guardar em cada inscrição: nome e turma.' },
        'v-dad-vagas': { quality: 'essencial', feedback: 'O limite de vagas de cada turma.', missing: 'Diga que cada turma tem um número máximo de vagas.' },
        'v-dad-ordem': { quality: 'util', feedback: 'Útil se houver lista de espera, mas não é o foco agora.' },
        'v-dad-documentos': { quality: 'irrelevante', feedback: 'Documentos pessoais não são necessários para se inscrever em um curso gratuito.' },
        'v-aco-inscrever': { quality: 'essencial', feedback: 'Registrar inscrições.', missing: 'O pedido precisa dizer que as inscrições devem ser registradas.' },
        'v-aco-limite': { quality: 'essencial', feedback: 'Regra de capacidade.', missing: 'Falta dizer o que fazer quando a turma estiver cheia.' },
        'v-aco-duplicada': { quality: 'essencial', feedback: 'Regra de duplicidade — o problema principal de Rafael.', missing: 'Falta dizer o que fazer quando a pessoa já está inscrita na turma.' },
        'v-aco-cancelar': { quality: 'util', feedback: 'Cancelar é útil, mas não é o que Rafael pediu agora.' },
        'v-aco-espera': { quality: 'util', feedback: 'Lista de espera é uma boa ideia para o futuro.' },
        'v-aco-promover': { quality: 'util', feedback: 'Útil quando houver lista de espera.' },
        'v-aco-ultimo': { quality: 'irrelevante', feedback: 'Chamar o último da fila não é justo — e não há fila nesta variação.' },
        'v-res-claras': { quality: 'essencial', feedback: 'Mensagens claras ajudam quem está no balcão.', missing: 'Peça que a ferramenta explique o motivo de cada recusa.' },
        'v-res-justica': { quality: 'util', feedback: 'Justo, mas não há fila nesta variação.' },
        'v-res-lotar': { quality: 'prejudicial', feedback: 'Lotar demais deixa gente sem computador — o contrário do que Rafael precisa.' },
        'v-res-dados': { quality: 'util', feedback: 'Bom cuidado: evita guardar dados desnecessários.' },
        'v-resu-turmas': { quality: 'essencial', feedback: 'Mostra vagas ocupadas e inscritos.', missing: 'Diga o que mostrar: vagas ocupadas e inscritos de cada turma.' },
        'v-resu-fila': { quality: 'util', feedback: 'Útil se houver lista de espera.' },
        'v-resu-ranking': { quality: 'irrelevante', feedback: 'Um ranking não ajuda a controlar vagas e pode expor as pessoas.' },
        'v-ver-repetida': { quality: 'essencial', feedback: 'Teste concreto da duplicidade.', missing: 'Inclua um teste de inscrição repetida.' },
        'v-ver-cheia': { quality: 'essencial', feedback: 'Teste concreto da capacidade.', missing: 'Inclua um teste com turma cheia.' },
        'v-ver-fila': { quality: 'irrelevante', feedback: 'Não há lista de espera nesta variação.' },
        'v-ver-vago': { quality: 'vago', feedback: '“Testar tudo direitinho” não diz o que testar.' },
      },
      tool: {
        kind: 'enrollment',
        people: ['Ana Paula', 'Joaquim', 'Rosa', 'Tiago', 'Marcos', 'Helena', 'Bianca', 'Davi'],
        courses: [
          { id: 'info', name: 'Informática básica', schedule: 'Sábados, 9h', capacity: 4, confirmed: ['Ana Paula', 'Joaquim'], waitlist: [] },
          { id: 'planilhas', name: 'Planilhas para pequenos negócios', schedule: 'Quartas, 19h', capacity: 2, confirmed: ['Rosa', 'Tiago'], waitlist: [] },
        ],
      },
      tests: [
        {
          id: 't-valida',
          title: 'Fazer uma inscrição válida',
          instruction: 'Inscreva Marcos em Informática básica (2 de 4 vagas ocupadas).',
          expected: 'A inscrição é confirmada e a turma fica com 3 de 4 vagas ocupadas.',
          check: 'enr.valid',
          autoActions: [{ type: 'enr.enroll', person: 'Marcos', courseId: 'info' }],
        },
        {
          id: 't-repetida',
          title: 'Repetir uma inscrição',
          instruction: 'Inscreva Joaquim de novo em Informática básica (ele já está inscrito).',
          expected: 'A ferramenta avisa que Joaquim já está inscrito e não ocupa outra vaga.',
          check: 'enr.duplicate',
          autoActions: [{ type: 'enr.enroll', person: 'Joaquim', courseId: 'info' }],
        },
        {
          id: 't-cheia',
          title: 'Tentar entrar em uma turma cheia',
          instruction: 'Inscreva Helena em Planilhas para pequenos negócios (2 de 2 vagas ocupadas).',
          expected: 'A inscrição não é confirmada e a ferramenta explica que a turma está cheia.',
          check: 'enr.full',
          autoActions: [{ type: 'enr.enroll', person: 'Helena', courseId: 'planilhas' }],
        },
      ],
      impact:
        'Cada pessoa ocupa uma única vaga, e as turmas não passam do número de computadores. Quem chega para a aula encontra o seu lugar, e nenhuma vaga é desperdiçada por engano.',
      takeaways: [
        'Guardar um dado (o número de vagas) não é o mesmo que criar uma regra para respeitá-lo.',
        'Duas regras diferentes precisam de dois testes diferentes.',
        'Testes podem ser inconclusivos: às vezes outra regra barra a ação antes. Escolher bem a situação de teste faz diferença.',
      ],
    },
    {
      id: 'vagas-b',
      scenarioId: 'vagas',
      letter: 'B',
      title: 'Lista de espera justa',
      situation:
        '“A turma de internet segura está cheia e tem gente esperando. Quando alguém desiste, a vaga fica parada dias — ou acaba indo para quem pediu por último, porque é quem está com a conversa aberta no celular.”',
      goal: 'Ajudar Rafael a organizar a lista de espera e chamar a primeira pessoa da fila quando surgir uma vaga.',
      learning: 'Entender a ideia de fila (ordem de chegada) e testar uma sequência de ações, não só uma ação isolada.',
      questions: [
        {
          id: 'q-quem',
          text: 'Quem vai usar a ferramenta?',
          answer: 'Eu e a Cris. Quando alguém desiste, quem estiver no balcão precisa saber na hora quem chamar.',
          reveals: ['f-usuarios'],
          why: 'Saber quem usa mostra que a ferramenta precisa dizer claramente quem foi chamado.',
          usefulness: 'util',
        },
        {
          id: 'q-registra',
          text: 'O que você precisa registrar?',
          answer: 'Nome e turma, o limite de vagas e, quando a turma lota, a lista de espera na ordem em que as pessoas chegaram.',
          reveals: ['f-dados'],
          why: 'A ordem de chegada é um dado: sem guardá-la, não há como ser justo.',
          usefulness: 'essencial',
        },
        {
          id: 'q-errado',
          text: 'O que costuma dar errado?',
          answer: 'Alguém desiste, a vaga fica vazia e ninguém lembra de chamar quem estava esperando. Ou chamam quem pediu por último, e quem esperou mais fica chateado — com razão.',
          reveals: ['f-problema'],
          why: 'O problema tem duas partes: vaga parada e ordem desrespeitada.',
          usefulness: 'essencial',
        },
        {
          id: 'q-sem-vagas',
          text: 'O que deve acontecer quando não houver vagas?',
          answer: 'A pessoa entra na lista de espera e fica sabendo a sua posição.',
          reveals: ['f-regra-espera'],
          why: 'Você descobriu o que fazer quando a turma enche: em vez de recusar, colocar na fila.',
          usefulness: 'essencial',
        },
        {
          id: 'q-desistencia',
          text: 'E quando alguém cancelar a inscrição?',
          answer: 'A vaga tem que ir para a primeira pessoa da lista, automaticamente, e a gente avisa essa pessoa.',
          reveals: ['f-regra-promocao'],
          why: 'Perguntar “o que deve acontecer quando…” revela a regra principal desta missão.',
          usefulness: 'essencial',
        },
        {
          id: 'q-fila-hoje',
          text: 'Quem está na lista de espera hoje?',
          answer: 'O Severino chegou primeiro, depois a Lia. Os dois querem muito a turma de internet segura.',
          reveals: ['f-fila'],
          why: 'Saber a situação atual ajuda a planejar testes realistas.',
          usefulness: 'util',
        },
        {
          id: 'q-conferir',
          text: 'Como vamos saber se está funcionando?',
          answer: 'Com a turma cheia, colocar alguém na lista de espera. Depois, cancelar uma inscrição e ver se quem estava em primeiro — o Severino — foi chamado.',
          reveals: ['f-verificacao'],
          why: 'Esses exemplos viram os testes que você vai fazer depois.',
          usefulness: 'essencial',
        },
        {
          id: 'q-certificado',
          text: 'Os cursos dão certificado?',
          answer: 'Dão, sim! Mas isso é com outra equipe.',
          reveals: [],
          why: 'Não muda o funcionamento da lista de espera. Perguntar o que acontece quando alguém cancela ajuda mais.',
          usefulness: 'pouco-util',
        },
      ],
      facts: [
        { id: 'f-usuarios', kind: 'usuarios', essential: false, text: 'Rafael e Cris, no balcão, precisam saber na hora quem chamar.' },
        {
          id: 'f-dados',
          kind: 'dados',
          essential: true,
          text: 'Nome, turma, limite de vagas e a lista de espera na ordem de chegada.',
          concept: { term: 'Dados', explanation: 'As informações que uma ferramenta guarda são chamadas de dados — inclusive a ordem em que as coisas aconteceram.' },
        },
        { id: 'f-problema', kind: 'problema', essential: true, text: 'Vagas ficam paradas, ou vão para quem pediu por último.' },
        {
          id: 'f-regra-espera',
          kind: 'regras',
          essential: true,
          text: 'Com a turma cheia, a pessoa entra na lista de espera e recebe sua posição.',
          concept: { term: 'Fila', explanation: 'Quando quem chega primeiro é atendido primeiro, temos uma fila. Em tecnologia, filas são muito comuns.' },
        },
        {
          id: 'f-regra-promocao',
          kind: 'regras',
          essential: true,
          text: 'Quando uma vaga abre, a primeira pessoa da lista é confirmada e avisada.',
          concept: {
            term: 'Regra de negócio',
            explanation: 'Você descobriu uma condição que a solução precisa respeitar: chamar a primeira pessoa da fila. Isso é uma regra de negócio.',
          },
        },
        { id: 'f-fila', kind: 'resultado', essential: false, text: 'Hoje a lista de espera tem Severino (1º) e Lia (2º).' },
        {
          id: 'f-verificacao',
          kind: 'verificacao',
          essential: true,
          text: 'Turma cheia leva para a lista; ao cancelar uma inscrição, Severino (primeiro da fila) é chamado.',
          concept: { term: 'Caso de teste', explanation: 'Uma situação concreta usada para conferir se a solução funciona é chamada de caso de teste.' },
        },
      ],
      help: {
        briefing: {
          pista: 'Rafael tem dois problemas com as vagas que abrem. Quais são?',
          exemplo: 'A vaga fica parada, ou vai para a pessoa errada.',
          direta: 'Clique em “Começar a investigar” para conversar com Rafael.',
        },
        investigate: {
          pista: 'Pense em duas situações: quando a turma enche e quando alguém desiste.',
          exemplo: 'Pergunte: “E quando alguém cancelar a inscrição?”',
          direta: 'Faça as perguntas sobre o que registrar, o que dá errado, turma sem vagas, cancelamento e como conferir.',
        },
        build: {
          pista: 'Para chamar a pessoa certa, a ferramenta precisa de três coisas: lista de espera, cancelamento e uma regra de quem chamar.',
          exemplo: 'Sem o bloco de cancelamento, não existe vaga abrindo. Sem a regra de quem chamar, a vaga abre e fica parada.',
          direta: 'Inclua: objetivo com lista de espera; contexto da biblioteca e das desistências; nome, turma, vagas e ordem; inscrever, limitar, lista de espera, cancelar e chamar o primeiro; ordem de chegada respeitada; mostrar turmas e fila; e o teste da fila.',
        },
        test: {
          pista: 'O terceiro teste depende de uma sequência: alguém na fila e depois um cancelamento.',
          exemplo: 'Depois de cancelar, olhe quem saiu da lista de espera. Era quem chegou primeiro?',
          direta: 'Se ninguém foi chamado, inclua “confirmar automaticamente a primeira pessoa da lista”. Se foi chamada a pessoa errada, remova o bloco que chama o último.',
        },
      },
      blockRoles: {
        'v-obj-fila': { quality: 'essencial', feedback: 'Objetivo claro: inscrições e lista de espera.', missing: 'Falta dizer o objetivo: organizar inscrições e lista de espera.' },
        'v-obj-inscricoes': { quality: 'util', feedback: 'Fala de vagas, mas não da lista de espera, que é o problema desta missão.' },
        'v-obj-vago': { quality: 'vago', feedback: '“Inovador” não diz o que a ferramenta precisa resolver.' },
        'v-obj-certificado': { quality: 'irrelevante', feedback: 'Certificados não resolvem a lista de espera.' },
        'v-ctx-biblioteca': { quality: 'essencial', feedback: 'Diz onde e como as inscrições acontecem.', missing: 'Conte onde os cursos acontecem e como as inscrições são feitas.' },
        'v-ctx-desistencia': { quality: 'essencial', feedback: 'Explica o problema de hoje: vagas paradas.', missing: 'Conte o problema de hoje: desistências deixam vagas paradas.' },
        'v-ctx-repetida': { quality: 'util', feedback: 'Problema real, mas é o foco da outra variação.' },
        'v-ctx-predio': { quality: 'irrelevante', feedback: 'A reforma do prédio não ajuda a IA a organizar a fila.' },
        'v-dad-inscricao': { quality: 'essencial', feedback: 'Nome e turma de cada inscrição.', missing: 'Diga quais informações guardar em cada inscrição: nome e turma.' },
        'v-dad-vagas': { quality: 'essencial', feedback: 'O limite de vagas de cada turma.', missing: 'Diga que cada turma tem um número máximo de vagas.' },
        'v-dad-ordem': { quality: 'essencial', feedback: 'Sem a ordem de chegada, não há como ser justo.', missing: 'Peça para guardar a ordem de chegada na lista de espera.' },
        'v-dad-documentos': { quality: 'irrelevante', feedback: 'Documentos pessoais não são necessários para entrar na fila.' },
        'v-aco-inscrever': { quality: 'essencial', feedback: 'Registrar inscrições.', missing: 'O pedido precisa dizer que as inscrições devem ser registradas.' },
        'v-aco-limite': { quality: 'essencial', feedback: 'Regra de capacidade.', missing: 'Falta dizer que turma cheia não confirma novas inscrições.' },
        'v-aco-espera': { quality: 'essencial', feedback: 'Coloca na fila quem chega com a turma cheia.', missing: 'Falta dizer o que fazer quando a turma enche: lista de espera.' },
        'v-aco-cancelar': { quality: 'essencial', feedback: 'Sem cancelamento, nenhuma vaga abre.', missing: 'Falta permitir cancelar inscrições.' },
        'v-aco-promover': { quality: 'essencial', feedback: 'Regra principal: chamar a primeira pessoa da fila.', missing: 'Falta dizer quem chamar quando uma vaga abre.' },
        'v-aco-duplicada': { quality: 'util', feedback: 'Boa regra, mas não é o foco desta variação.' },
        'v-aco-ultimo': { quality: 'prejudicial', feedback: 'Chamar o último da fila é exatamente o que deixou as pessoas chateadas.' },
        'v-res-claras': { quality: 'essencial', feedback: 'Mensagens claras ajudam a avisar as pessoas.', missing: 'Peça que a ferramenta explique cada situação em linguagem simples.' },
        'v-res-justica': { quality: 'essencial', feedback: 'Garante a ordem de chegada.', missing: 'Diga que ninguém pode passar na frente de quem chegou antes.' },
        'v-res-lotar': { quality: 'prejudicial', feedback: 'Se ninguém é recusado, a lista de espera nunca é usada e a turma lota demais.' },
        'v-res-dados': { quality: 'util', feedback: 'Bom cuidado: evita guardar dados desnecessários.' },
        'v-resu-turmas': { quality: 'essencial', feedback: 'Mostra vagas ocupadas e inscritos.', missing: 'Diga o que mostrar: vagas ocupadas e inscritos de cada turma.' },
        'v-resu-fila': { quality: 'essencial', feedback: 'Mostra a fila em ordem.', missing: 'Peça para mostrar a lista de espera com a posição de cada pessoa.' },
        'v-resu-ranking': { quality: 'irrelevante', feedback: 'Um ranking não ajuda a organizar a fila e pode expor as pessoas.' },
        'v-ver-fila': { quality: 'essencial', feedback: 'Teste concreto da regra principal.', missing: 'Inclua um teste: cancelar com duas pessoas na fila e ver quem é chamado.' },
        'v-ver-cheia': { quality: 'util', feedback: 'Bom teste, mas não verifica quem é chamado da fila.' },
        'v-ver-repetida': { quality: 'util', feedback: 'Bom teste, mas não é o foco desta variação.' },
        'v-ver-vago': { quality: 'vago', feedback: '“Testar tudo direitinho” não diz o que testar.' },
      },
      tool: {
        kind: 'enrollment',
        people: ['Bianca', 'Davi', 'Helena', 'Severino', 'Lia', 'Tiago', 'Marcos', 'Joana'],
        courses: [
          {
            id: 'internet',
            name: 'Internet segura para o dia a dia',
            schedule: 'Terças, 18h',
            capacity: 3,
            confirmed: ['Bianca', 'Davi', 'Helena'],
            waitlist: ['Severino', 'Lia'],
          },
          { id: 'celular', name: 'Celular sem mistério', schedule: 'Sextas, 15h', capacity: 4, confirmed: ['Marcos'], waitlist: [] },
        ],
      },
      tests: [
        {
          id: 't-espera',
          title: 'Entrar na lista de espera',
          instruction: 'Inscreva Tiago em Internet segura para o dia a dia (turma cheia: 3 de 3).',
          expected: 'Tiago entra na lista de espera, na 3ª posição, e a turma continua com 3 pessoas.',
          check: 'enr.waitlist',
          autoActions: [{ type: 'enr.enroll', person: 'Tiago', courseId: 'internet' }],
        },
        {
          id: 't-cancelar',
          title: 'Cancelar uma inscrição confirmada',
          instruction: 'Cancele a inscrição de Davi em Internet segura para o dia a dia.',
          expected: 'Davi sai da turma e a vaga dele é liberada.',
          check: 'enr.cancelConfirmed',
          autoActions: [{ type: 'enr.cancel', person: 'Davi', courseId: 'internet' }],
        },
        {
          id: 't-promocao',
          title: 'Verificar a promoção na ordem correta',
          instruction: 'Com pelo menos duas pessoas na lista de espera, cancele uma inscrição confirmada da turma (por exemplo, a de Bianca) e veja quem é chamado.',
          expected: 'Quem está em primeiro na fila (no começo, Severino) tem a inscrição confirmada, e os demais sobem uma posição.',
          check: 'enr.promotionOrder',
          autoActions: [{ type: 'enr.cancel', person: 'Bianca', courseId: 'internet' }],
        },
      ],
      impact:
        'Quando alguém desiste, a vaga vai na hora para quem esperava há mais tempo. Ninguém fura a fila, nenhuma vaga fica parada e o balcão sabe exatamente quem avisar.',
      takeaways: [
        'Uma fila só é justa se a ferramenta guardar a ordem de chegada e tiver uma regra clara de quem chamar.',
        'Alguns testes exigem uma sequência de ações: primeiro alguém entra na fila, depois alguém cancela.',
        'Um bloco plausível (“chamar o interesse mais recente”) pode contrariar o que a pessoa realmente precisa.',
      ],
    },
  ],
};
